fives_json = {
    "aback": "toward or situated to the rear; taken by surprise",
    "abase": "to behave in a way that belittles or degrades someone",
    "abate": "to become less intense or widespread",
    "abbey": "a building occupied by a community of monks or nuns",
    "abbot": "a man who is the head of an abbey of monks",
    "abhor": "to regard with disgust and hatred",
    "abide": "to accept or act in accordance with a rule or decision",
    "abler": "comparative form of able; having greater skill or power",
    "abode": "a place of residence; a house or home",
    "abort": "to carry out or undergo the abortion of a fetus",
    "about": "on the subject of; concerning",
    "above": "at a higher level or layer than",
    "abuse": "to use something to bad effect or for a bad purpose",
    "abyss": "a deep or seemingly bottomless chasm",
    "ached": "suffered a continuous dull pain",
    "aches": "a continuous or prolonged dull pain in a part of one's body",
    "acids": "plural of acid; substances with particular chemical properties",
    "acing": "excelling at something, like getting an 'A' on a test",
    "acorn": "the nut of the oak tree, a smooth oval in a rough cup",
    "acres": "a unit of land area equal to 4,840 square yards",
    "acrid": "having an irritatingly strong and unpleasant taste or smell",
    "acted": "took action; did something",
    "actor": "a person whose profession is acting on stage, in films, or on television",
    "acute": "present or experienced to a severe or intense degree",
    "adage": "a proverb or short statement expressing a general truth",
    "adapt": "to make something suitable for a new use or purpose",
    "added": "joined something to something else so as to increase the size, number, or amount",
    "adder": "a small venomous Eurasian snake",
    "addle": "to make someone unable to think clearly; confuse",
    "adept": "very skilled or proficient at something",
    "adieu": "a goodbye",
    "adios": "a Spanish term used to say goodbye",
    "admit": "to confess to be true or to be the case",
    "adobe": "a kind of clay used as a building material",
    "adopt": "to legally take another's child and bring it up as one's own",
    "adore": "to love and respect someone deeply",
    "adorn": "to make more beautiful or attractive",
    "adult": "a person who is fully grown or developed",
    "aegis": "the protection, backing, or support of a particular person or organization",
    "affix": "to stick, attach, or fasten something to something else",
    "afire": "on fire",
    "afoot": "in preparation or progress; happening or beginning to happen",
    "afoul": "into conflict or difficulty with",
    "after": "in the time following an event or another period of time",
    "again": "another time; once more",
    "agape": "with the mouth wide open, especially in surprise or wonder",
    "agate": "a hard stone with bands of color, used in jewelry",
    "agent": "a person who acts on behalf of another",
    "agile": "able to move quickly and easily",
    "aging": "the process of growing old",
    "aglow": "glowing",
    "agony": "extreme physical or mental suffering",
    "agree": "to have the same opinion about something; concur",
    "ahead": "further forward in space; in the line of one's forward movement",
    "ahold": "a grip on something",
    "aided": "provided with help or support",
    "aider": "a person or thing that helps or provides aid",
    "aides": "people who help or act as assistants",
    "ailed": "troubled or afflicted",
    "aimed": "pointed or directed a weapon or camera at a target",
    "aioli": "a Provençal sauce made of garlic, olive oil, and egg yolks",
    "aired": "ventilated; expressed an opinion publicly",
    "aisle": "a passage between rows of seats in a building",
    "alarm": "an anxious awareness of danger",
    "album": "a collection of recordings or photographs",
    "alder": "a type of tree related to the birch",
    "alert": "quick to notice any unusual and potentially dangerous or difficult circumstances",
    "algae": "a simple, non-flowering plant that grows in water",
    "alibi": "a claim or piece of evidence that one was elsewhere when an act was committed",
    "alien": "a being from another world",
    "align": "to place or arrange things in a straight line",
    "alike": "similar to each other",
    "alive": "living, not dead",
    "alkyd": "a synthetic resin used in paints and varnishes",
    "allay": "to diminish or put to rest fear, suspicion, or worry",
    "alley": "a narrow passageway between or behind buildings",
    "allot": "to give or apportion something to someone",
    "allow": "to let someone have or do something",
    "alloy": "a metal made by combining two or more metallic elements",
    "aloft": "up in or into the air; overhead",
    "alone": "having no one else present; on one's own",
    "along": "moving in a constant direction on a road, path, or other surface",
    "aloof": "not friendly or forthcoming; cool and distant",
    "aloud": "audibly; not silently or in a whisper",
    "alpha": "the first letter of the Greek alphabet",
    "altar": "a table or flat-topped block used for religious rites",
    "alter": "to change or cause to change in character or composition",
    "amass": "to gather together or accumulate a large amount of something",
    "amaze": "to surprise someone greatly; astonish",
    "amber": "hard translucent fossilized resin, typically yellow",
    "amble": "to walk or move at a slow, relaxed pace",
    "amend": "to make minor changes to a text to make it fairer or more accurate",
    "amide": "a compound derived from ammonia by replacement of a hydrogen atom by a metal",
    "amigo": "a Spanish word for friend",
    "amino": "relating to an amine, a type of organic compound",
    "amiss": "not quite right; inappropriate or out of place",
    "amity": "a friendly relationship",
    "among": "situated more or less centrally in relation to several other things",
    "ample": "enough or more than enough; plentiful",
    "amply": "enough or more than enough; sufficiently",
    "amuse": "to cause someone to find something funny",
    "angel": "a spiritual being believed to act as a messenger of God",
    "anger": "a strong feeling of annoyance, displeasure, or hostility",
    "angle": "the space between two intersecting lines or surfaces at or close to the point where they meet",
    "angry": "feeling or showing strong annoyance, displeasure, or hostility",
    "angst": "a feeling of deep anxiety or dread",
    "anime": "a style of Japanese film and television animation",
    "ankle": "the joint connecting the foot with the leg",
    "annex": "to add as an extra or subordinate part",
    "annoy": "to irritate someone; make someone a little angry",
    "annul": "to declare invalid an official agreement, decision, or result",
    "anode": "the positively charged electrode by which electrons leave an electrical device",
    "antic": "grotesque or bizarre",
    "anvil": "a heavy iron block on which metal can be hammered and shaped",
    "aorta": "the main artery of the body, supplying oxygenated blood to the circulatory system",
    "apace": "swiftly; quickly",
    "apart": "separated by a distance or by time",
    "aphid": "a small bug that feeds by sucking sap from plants",
    "apnea": "temporary cessation of breathing, especially during sleep",
    "apple": "the round fruit of a tree of the rose family",
    "apply": "to make a formal application or request",
    "apron": "a protective garment worn over the front of one's clothes",
    "aptly": "in a manner that is appropriate or suitable in the circumstances",
    "arbor": "a shady garden alcove with sides and a roof formed by trees or climbing plants",
    "ardor": "enthusiasm or passion",
    "arena": "a level area surrounded by seats for spectators, used for sports or other entertainment",
    "argue": "to give reasons or cite evidence in support of an idea, action, or theory",
    "arise": "to begin to occur or to exist",
    "armed": "equipped with or carrying a weapon or weapons",
    "armor": "the metal coverings formerly worn to protect the body in battle",
    "aroma": "a distinctive, typically pleasant smell",
    "arose": "past tense of arise",
    "array": "an impressive display or range of a particular type of thing",
    "arrow": "a weapon consisting of a thin, straight stick with a sharp point, designed to be shot from a bow",
    "arson": "the criminal act of deliberately setting fire to property",
    "ashen": "very pale from shock, fear, or illness",
    "aside": "to one side; out of the way",
    "asked": "past tense of ask; said something in order to obtain an answer or information",
    "askew": "not in a straight or level position",
    "aspen": "a kind of poplar tree with small, rounded leaves",
    "aspic": "a savory jelly made with meat stock, set in a mold and used to contain pieces of meat, seafood, or eggs",
    "assay": "to test the quality of something, especially metal or ore",
    "asset": "a useful or valuable thing, person, or quality",
    "atlas": "a book of maps or charts",
    "atoll": "a ring-shaped reef, island, or chain of islands formed of coral",
    "atone": "to make amends or reparation for a wrong",
    "attic": "a space or room just below the roof of a building",
    "audio": "sound, especially when recorded, transmitted, or reproduced",
    "audit": "an official inspection of an organization's accounts",
    "auger": "a tool for boring holes in wood",
    "aught": "anything at all",
    "augur": "to portend a good or bad outcome",
    "aunts": "plural of aunt; the sister of one's father or mother",
    "aunty": "informal for aunt",
    "avail": "to help or benefit",
    "avert": "to turn away one's eyes or thoughts",
    "avian": "relating to birds",
    "avoid": "to keep away from or stop oneself from doing something",
    "await": "to wait for an event to happen",
    "awake": "not asleep",
    "award": "to give something as a prize for an achievement",
    "aware": "having knowledge or perception of a situation or fact",
    "awash": "covered or flooded with water",
    "awful": "very bad or unpleasant",
    "awoke": "past tense of awake",
    "axial": "relating to or forming an axis",
    "axiom": "a statement or proposition which is regarded as being established, accepted, or self-evidently true",
    "axion": "a hypothetical subatomic particle",
    "azure": "bright blue in color, like a cloudless sky",
    "bacon": "cured meat from the back or sides of a pig",
    "badge": "a distinctive emblem worn as a mark of office, membership, achievement, or licensed employment",
    "badly": "in a poor manner or to a poor standard; inadequately",
    "bagel": "a dense bread roll in the shape of a ring",
    "baggy": "loose and hanging in folds",
    "bails": "the crosspieces bridging the stumps in cricket",
    "bairn": "a Scottish word for a child",
    "baits": "plural of bait; food used to entice fish or animals",
    "baked": "cooked by dry heat without direct exposure to a flame",
    "baker": "a person whose trade is making and selling bread and pastries",
    "baler": "a machine for making bales of hay or paper",
    "balky": "unwilling to proceed; hesitant",
    "balls": "plural of ball; a solid or hollow spherical object",
    "balmy": "pleasantly warm",
    "banal": "so lacking in originality as to be obvious and boring",
    "bandy": "to discuss a idea or rumor casually",
    "banjo": "a stringed musical instrument with a circular body",
    "banns": "a notice read in church announcing a proposed marriage",
    "barbs": "sharp projections, especially on a wire or arrow",
    "bards": "poets, traditionally ones reciting epics",
    "bared": "uncovered; made visible",
    "barge": "a flat-bottomed boat for carrying freight",
    "baron": "a member of the lowest order of the British nobility",
    "basal": "forming or belonging to a bottom layer or base",
    "based": "having a specified main place of operation",
    "basic": "forming an essential foundation or starting point",
    "basil": "an aromatic herb of the mint family",
    "basin": "a bowl for washing, typically attached to a wall",
    "basis": "the underlying support or foundation for an idea, argument, or process",
    "basks": "lies exposed to warmth and light for relaxation",
    "basso": "a bass singer or a part for a bass voice",
    "batch": "a quantity of something produced at one time",
    "bated": "in suspense; excited or anxious",
    "bathe": "to wash oneself or soak in a bath",
    "baton": "a thin stick used by a conductor to direct an orchestra",
    "batty": "mad; insane",
    "bawdy": "humorously or vulgarly indecent",
    "bayed": "barked or howled loudly, especially of a dog",
    "bayou": "a marshy outlet of a lake or river",
    "beach": "a pebbly or sandy shore by the ocean",
    "beads": "small pieces of material with a hole for threading",
    "beady": "small, round, and glittering eyes",
    "beaks": "plural of beak; a bird's horny projecting jaws",
    "beams": "long, sturdy pieces of squared timber or metal",
    "beard": "hair growing on a man's chin and cheeks",
    "bears": "large, heavy mammals with thick fur",
    "beast": "an animal, especially a large or dangerous four-footed one",
    "beats": "defeats; a regular rhythm in music",
    "beaus": "plural of beau; a boyfriend or male admirer",
    "beaut": "an excellent or beautiful example of something",
    "beaux": "the plural form of beau",
    "bebop": "a type of jazz characterized by fast tempo and complex harmonies",
    "becks": "a gesture requesting silence, attention, or someone's presence",
    "bedim": "to make dim or obscure",
    "beech": "a large tree with smooth gray bark",
    "beefy": "muscular or robust",
    "befit": "to be appropriate for; suit",
    "befog": "to make confused or unclear",
    "began": "past tense of begin",
    "begat": "archaic term for fathered a child",
    "beget": "to produce or cause to happen",
    "begin": "to start; to perform the first part of an action",
    "begun": "past participle of begin",
    "beige": "a pale sandy fawn color",
    "being": "existence; a living creature",
    "belay": "to secure a rope by winding it around a cleat or pin",
    "belch": "to emit gas noisily from the stomach through the mouth",
    "belie": "to fail to give a true impression of something",
    "belle": "a beautiful and charming woman",
    "bells": "hollow metal objects that sound a clear musical note when struck",
    "belly": "the front part of the human trunk below the ribs",
    "below": "at a lower level or layer than",
    "belts": "strips of leather or other material worn around the waist",
    "bench": "a long seat for several people",
    "bends": "curves in a road, river, or path",
    "bendy": "able to be bent easily; flexible",
    "benny": "slang for an amphetamine pill",
    "beret": "a round, flat, brimless cap of felt",
    "berry": "a small, roundish juicy fruit without a stone",
    "berth": "a ship's allotted place at a wharf or dock",
    "beryl": "a transparent pale green, blue, or yellow mineral",
    "beset": "to be troubled or afflicted persistently",
    "betel": "a leaf chewed in Asia with the betel nut",
    "bevel": "a slope from the horizontal or vertical in carpentry",
    "bevvy": "slang for a drink, especially an alcoholic one",
    "bible": "the Christian scriptures",
    "biddy": "a hen; or a derogatory term for an old woman",
    "bided": "remained in a condition or state",
    "bides": "awaits a favorable opportunity",
    "bidet": "a low basin used for washing one's genital and anal area",
    "biers": "frames for coffins",
    "biffs": "blows or punches",
    "bight": "a curve or recess in a coastline",
    "bigot": "a person who is intolerant toward those holding different opinions",
    "bijou": "a jewel; something small and elegant",
    "biked": "rode a bicycle",
    "biker": "a person who rides a bicycle or motorcycle",
    "bikes": "plural of bike; bicycles or motorcycles",
    "biles": "a bitter greenish-brown fluid aiding digestion",
    "bilge": "the area on the outer surface of a ship's hull where the bottom curves to meet the vertical sides",
    "bills": "amounts of money owed for goods or services",
    "billy": "a male goat; or a club",
    "bimbo": "an attractive but unintelligent woman",
    "bindi": "a decorative mark worn in the middle of the forehead by Indian women",
    "binge": "a period of excessive indulgence",
    "bingo": "a game in which players mark off numbers on cards",
    "biome": "a large natural community of flora and fauna",
    "biota": "the animal and plant life of a particular region",
    "biped": "an animal that uses two legs for walking",
    "birch": "a slender tree with thin, peeling bark",
    "birth": "the emergence of a baby from the body of its mother",
    "bison": "a humpbacked shaggy-haired wild ox",
    "bitch": "a female dog; a spiteful or unpleasant woman",
    "biter": "someone or something that bites",
    "bites": "uses teeth to cut into something",
    "bitty": "made up of small parts that seem unrelated",
    "black": "of the very darkest color",
    "blade": "the flat part of a tool or weapon",
    "blame": "to assign responsibility for a fault or wrong",
    "bland": "lacking strong features or characteristics",
    "blank": "not written or printed on",
    "blare": "to make a loud, harsh sound",
    "blast": "a destructive wave of highly compressed air",
    "blaze": "a very large or fiercely burning fire",
    "bleak": "lacking vegetation and exposed to the elements",
    "bleat": "the weak crying of a sheep, goat, or calf",
    "bleed": "to lose blood from the body",
    "bleep": "a short high-pitched sound made by an electronic device",
    "blend": "to mix a substance with another substance",
    "bless": "to pronounce words in a religious rite",
    "blimp": "a small nonrigid airship",
    "blind": "unable to see",
    "blink": "to shut and open the eyes quickly",
    "blips": "short high-pitched sounds; minor setbacks",
    "bliss": "perfect happiness; great joy",
    "blitz": "an intensive or sudden military attack",
    "bloat": "to swell with fluid or gas",
    "block": "a large solid piece of hard material",
    "bloke": "a man; a fellow",
    "blond": "having fair hair and a light complexion",
    "blood": "the red liquid that circulates in the arteries and veins",
    "bloom": "a flower, especially one cultivated for its beauty",
    "blown": "past participle of blow; moved by the wind",
    "blues": "a state of depression; a genre of music",
    "bluff": "to try to deceive someone as to one's intentions or abilities",
    "blunt": "having a worn-down edge or point; not sharp",
    "blurb": "a short description of a book, film, or other product",
    "blurt": "to say something suddenly and without careful consideration",
    "blush": "to become red in the face from embarrassment or shame",
    "board": "a long, thin, flat piece of wood",
    "boast": "to talk with excessive pride and self-satisfaction about one's achievements, possessions, or abilities",
    "boats": "small vessels for traveling on water",
    "bobby": "a British police officer",
    "bocce": "an Italian bowling game",
    "boded": "was a sign of a particular outcome",
    "bodes": "is a sign of a particular outcome",
    "bodge": "to make or repair something badly or clumsily",
    "bogey": "a score of one stroke over par on a hole in golf",
    "boggy": "too wet and muddy to be easily walked on; marshy",
    "bogie": "a low truck or trolley",
    "bogus": "not genuine or true; fake",
    "boils": "heats a liquid until it reaches its vaporization point",
    "bolas": "a weapon consisting of weights on the ends of interconnected cords",
    "boles": "the trunks of trees",
    "bolls": "the rounded seed capsules of plants such as cotton or flax",
    "bolts": "sliding bars for fastening a door",
    "bombe": "a frozen dessert, typically dome-shaped",
    "bombs": "explosive weapons",
    "boned": "having had the bones removed",
    "boner": "a stupid mistake; or an erection",
    "bones": "any of the pieces of hard, whitish tissue making up the skeleton",
    "boney": "alternative spelling of bony; having prominent bones",
    "bongo": "one of a pair of small drums played with the hands",
    "bonks": "hits or bumps lightly",
    "bonny": "attractive or beautiful",
    "bonus": "a sum of money added to a person's wages for good performance",
    "boobs": "slang for a woman's breasts",
    "booby": "a stupid person; a type of seabird",
    "booed": "showed disapproval or contempt by shouting 'boo'",
    "books": "written or printed works consisting of pages glued together",
    "booms": "periods of great prosperity or rapid economic growth",
    "boons": "things that are helpful or beneficial",
    "boors": "rough and bad-mannered people",
    "boost": "to help or encourage something to increase or improve",
    "booth": "a small temporary structure used for selling goods",
    "boots": "footwear that covers the foot and ankle",
    "booty": "valuable stolen goods, especially those seized in war",
    "booze": "alcoholic drink",
    "boozy": "involving large quantities of alcohol",
    "borax": "a white mineral used in making glass and as a cleaning agent",
    "bored": "feeling weary because one is unoccupied or lacks interest",
    "borer": "a tool or insect that makes holes",
    "bores": "makes a hole in something with a tool",
    "borne": "carried or transported by",
    "boron": "a chemical element",
    "bosom": "a woman's chest or breasts",
    "bossy": "fond of giving people orders; domineering",
    "botch": "to carry out a task badly or carelessly",
    "bough": "a main branch of a tree",
    "boule": "a material with a crystal structure; or a French form of bowls",
    "bound": "tied or fastened securely",
    "bowel": "the part of the alimentary canal below the stomach",
    "bower": "a pleasant shady place under trees or climbing plants",
    "bowls": "a game played with heavy balls rolled on a green",
    "boxed": "put into a box",
    "boxer": "a person who participates in the sport of boxing",
    "boxes": "containers with a flat base and sides",
    "boyar": "a member of the old aristocracy in Russia",
    "brace": "a device that clamps things tightly together or that gives support",
    "bract": "a modified leaf associated with a flower",
    "brads": "thin nails with small heads",
    "braes": "Scottish term for steep banks or hillsides",
    "brags": "says something in a boastful manner",
    "braid": "to interweave three or more strands of hair or other material",
    "brain": "an organ of soft nervous tissue contained in the skull",
    "brake": "a device for slowing or stopping a moving vehicle",
    "brand": "a type of product manufactured by a particular company",
    "brans": "the outer layers of cereal grains",
    "brash": "self-assertive in a rude, noisy, or overbearing way",
    "brass": "a yellow alloy of copper and zinc",
    "brave": "ready to face and endure danger or pain; showing courage",
    "bravo": "a cry of approval, especially for a performance",
    "brawl": "a rough or noisy fight or quarrel",
    "brawn": "physical strength in contrast to intelligence",
    "bread": "a food made of flour, water, and yeast mixed together and baked",
    "break": "to separate into pieces as a result of a blow, shock, or strain",
    "breed": "to mate and then produce offspring",
    "briar": "a prickly bush, especially a wild rose",
    "bribe": "to persuade someone to act in one's favor by a gift of money or other inducement",
    "brick": "a small rectangular block typically made of fired or sun-dried clay",
    "bride": "a woman on her wedding day or just before and after the event",
    "brief": "of short duration; not lasting for long",
    "brine": "water saturated or strongly impregnated with salt",
    "bring": "to take or go with someone or something to a place",
    "brink": "the extreme edge of land before a steep slope or a body of water",
    "briny": "of salty water or the sea; salty",
    "brisk": "active, fast, and energetic",
    "broad": "having a distance larger than usual from side to side; wide",
    "broil": "to cook by exposure to direct, intense radiant heat",
    "broke": "past tense of break; having completely run out of money",
    "brood": "a family of young animals, especially of a bird, produced at one hatching or birth",
    "brook": "a small stream",
    "broom": "a long-handled brush of bristles or twigs used for sweeping",
    "broth": "soup consisting of meat or vegetable chunks in a liquid",
    "brown": "of a color produced by mixing red, yellow, and black",
    "brows": "plural of brow; a person's forehead",
    "brunt": "the worst part or chief impact of a specified action",
    "brush": "an implement with a handle and a block of bristles",
    "brute": "a savagely violent person or animal",
    "bubba": "an informal term for brother",
    "bucks": "plural of buck; male deer; or dollars",
    "buddy": "a close friend",
    "budge": "to make or cause to make the slightest movement",
    "buffa": "an opera singer specializing in comic roles",
    "buggy": "a light, horse-drawn vehicle",
    "bugle": "a brass instrument like a small trumpet",
    "build": "to construct something by putting parts or material together",
    "built": "past tense of build",
    "bulbs": "the rounded underground storage organ of a plant",
    "bulge": "a rounded swelling which distorts an otherwise flat surface",
    "bulks": "the mass or magnitude of something large",
    "bulky": "taking up much space; large and unwieldy",
    "bulls": "male bovine animals",
    "bully": "a person who uses strength or power to harm or intimidate those who are weaker",
    "bumps": "raises a surface to form a rounded protuberance",
    "bumpy": "having a uneven surface with many patches raised above the rest",
    "bunch": "a number of things, typically of the same kind, growing or fastened together",
    "bundt": "a ring-shaped cake",
    "bunks": "narrow beds fixed to a wall",
    "bunny": "a child's term for a rabbit",
    "buoys": "anchored floats serving as navigation markers",
    "burbs": "short for suburbs",
    "burgs": "towns or cities",
    "burka": "a long, loose garment covering the whole body",
    "burly": "large and strong; heavily built",
    "burnt": "consumed, damaged, or destroyed by fire",
    "burps": "noisily releases air from the stomach through the mouth",
    "burro": "a small donkey used as a pack animal",
    "burrs": "rough edges left on an object after it has been made",
    "burst": "to break open or apart suddenly and violently",
    "bused": "transported by bus",
    "bushy": "growing thickly",
    "busts": "sculptures of a person's head, shoulders, and chest",
    "busty": "having large breasts",
    "butch": "having an appearance or manner that is traditionally masculine",
    "butte": "an isolated hill with steep sides and a flat top",
    "butts": "the thicker end of something, especially a tool or a weapon",
    "buxom": "of a woman plump, with a full figure and large breasts",
    "buyer": "a person who makes a purchase",
    "bylaw": "a rule made by a company or society to control the actions of its members",
    "bytes": "units of digital information",
    "cabby": "a taxi driver",
    "caber": "a tapered tree trunk tossed in the Scottish Highland sport",
    "cabin": "a private room on a ship",
    "cable": "a thick rope of wire or nonmetallic fiber",
    "cacao": "seeds from which cocoa and chocolate are made",
    "cache": "a collection of items of the same type stored in a hidden place",
    "cacti": "plural of cactus; succulent plants with spines",
    "caddy": "a person who carries a golfer's clubs",
    "cadet": "a young trainee in the armed services or police force",
    "cadre": "a small group of people specially trained for a particular purpose",
    "cafes": "plural of cafe; small restaurants selling light meals and drinks",
    "caged": "confined in a cage",
    "cages": "structures of bars or wires for confining animals",
    "cagey": "reluctant to give information owing to caution or suspicion",
    "cairn": "a mound of rough stones built as a memorial or landmark",
    "caked": "covered with a thick or hard layer of something",
    "calks": "metal projections on a horseshoe to prevent slipping",
    "calls": "cries out to someone in order to summon them",
    "calms": "makes someone tranquil and quiet",
    "calve": "to give birth to a calf",
    "calyx": "the sepals of a flower, typically forming a whorl",
    "camel": "a large, long-necked ungulate mammal of arid country",
    "cameo": "a piece of jewelry consisting of a portrait carved in relief",
    "campo": "a grassy plain in South America",
    "camps": "places with temporary accommodations of huts, tents, or other structures",
    "camus": "a type of plant; or the author Albert Camus",
    "canal": "an artificial waterway constructed to allow the passage of boats",
    "candy": "a sweet food made with sugar or syrup",
    "caned": "beaten with a cane as a punishment",
    "caner": "a person who makes chairs from cane",
    "canes": "plural of cane; the hollow jointed stem of a tall grass",
    "canna": "a tropical plant with bright flowers",
    "canny": "having or showing shrewdness and good judgment",
    "canoe": "a narrow, keelless boat with pointed ends",
    "canon": "a general law, rule, principle, or criterion",
    "canto": "one of the sections into which certain long poems are divided",
    "caped": "wearing a cape",
    "caper": "a playful skipping movement",
    "capes": "short cloaks",
    "capon": "a castrated rooster fattened for eating",
    "carat": "a unit of weight for precious stones and pearls",
    "carbs": "short for carbohydrates",
    "cards": "pieces of thick, stiff paper used for playing games",
    "cared": "felt concern or interest",
    "carer": "a family member or paid helper who looks after a sick or old person",
    "cares": "feels concern or interest",
    "cargo": "goods carried on a ship, aircraft, or motor vehicle",
    "carob": "a brown flour powder made from the seed pods of a tree",
    "carol": "a religious song or popular hymn associated with Christmas",
    "carom": "a shot in billiards in which the cue ball strikes two other balls",
    "carps": "complains or nags about something trivial",
    "carry": "to support and move someone or something from one place to another",
    "carte": "a menu or list of dishes available in a restaurant",
    "carts": "vehicles with either two or four wheels drawn by an animal",
    "carve": "to cut into a hard material to produce an object or design",
    "cased": "enclosed in a protective container",
    "cases": "instances of a particular situation or example",
    "casks": "barrels for holding liquids, like wine or beer",
    "catty": "spiteful; mean in a gossipy way",
    "cedar": "a type of fragrant, reddish wood",
    "chair": "a piece of furniture for one person to sit on",
    "chalk": "a white stick used for writing on blackboards",
    "charm": "the power of pleasing or attracting people",
    "chase": "to run after someone to catch them",
    "cheap": "low in price; not expensive",
    "cheat": "to act dishonestly to gain an advantage",
    "check": "to examine something to make sure it's correct",
    "cheek": "the side of your face below your eye",
    "cheer": "to shout for joy or to encourage",
    "chest": "a large, strong box for storage, or the front of the body",
    "chief": "the leader or most important person",
    "child": "a young human being",
    "chill": "a feeling of coldness, or to relax",
    "china": "a delicate ceramic material; plates and cups",
    "chirp": "a short, high sound made by a small bird",
    "chive": "a herb with long, thin leaves used in cooking",
    "choir": "a group of people who sing together",
    "choke": "to have difficulty breathing because of a blocked throat",
    "chore": "a routine task, especially a household one",
    "chunk": "a thick, solid piece of something",
    "civic": "relating to a city or citizens",
    "claim": "to state that something is true",
    "clamp": "a device for holding objects tightly together",
    "clash": "to come into conflict or disagree",
    "class": "a group of students, or a social rank",
    "clean": "free from dirt or mess",
    "clear": "easy to understand; transparent",
    "clerk": "a person who works in an office or helps customers",
    "click": "a short, sharp sound, or to press a button",
    "cliff": "a steep rock face, especially at the edge of the sea",
    "climb": "to go up something steep",
    "clock": "an instrument for measuring and showing time",
    "close": "to shut something, or near in distance",
    "cloth": "material made from weaving fibers",
    "cloud": "a white or gray mass in the sky made of water vapor",
    "clown": "a comic performer who wears funny clothes and makeup",
    "coach": "a person who trains athletes, or a type of bus",
    "coast": "the land near the sea; the shore",
    "cocoa": "a powder made from cacao beans, used to make chocolate",
    "crane": "a large machine for lifting heavy objects, or a type of bird",
    "daily": "happening or produced every day",
    "dairy": "a place where milk is stored or products like cheese are made",
    "daisy": "a common wildflower with white petals and a yellow center",
    "dance": "to move rhythmically to music",
    "dandy": "a man who is overly concerned with his clothes and appearance",
    "datum": "a single piece of information (plural: data)",
    "daunt": "to make someone feel intimidated or apprehensive",
    "dealt": "past tense of deal; distributed cards or handled a situation",
    "death": "the end of life",
    "debar": "to exclude or prohibit someone from a place or action",
    "debit": "an entry in an account recording a sum owed",
    "decaf": "coffee with most of its caffeine removed",
    "decal": "a design or picture that can be transferred to a surface",
    "decay": "to rot or decompose",
    "decor": "the furnishing and decoration of a room",
    "decoy": "something used to lure an animal or person into a trap",
    "defer": "to put off to a later time; postpone",
    "deity": "a god or goddess",
    "delay": "to make something happen later than planned",
    "delta": "a landform at the mouth of a river where it splits into several streams",
    "delve": "to reach inside a receptacle and search for something",
    "demon": "an evil spirit or devil",
    "denim": "a sturdy cotton fabric used for jeans",
    "dense": "closely compacted in substance; thick",
    "depot": "a place where buses, trains, or other vehicles are housed",
    "depth": "the distance from the top or surface to the bottom of something",
    "derby": "a sporting event or a type of hat",
    "deter": "to discourage someone from doing something",
    "detox": "a process of removing toxic substances from the body",
    "deuce": "a score of 40-40 in tennis, or the number two",
    "devil": "the supreme spirit of evil",
    "diary": "a book in which one keeps a daily record of events",
    "digit": "a finger, thumb, or toe, or a single number",
    "dilly": "something that is remarkable or outstanding",
    "diner": "a person eating a meal, or a small restaurant",
    "dingo": "a wild Australian dog",
    "dingy": "gloomy and drab in color or condition",
    "dirty": "covered with marks or stains; not clean",
    "disco": "a club or party for dancing to pop music",
    "ditch": "a narrow channel dug in the ground, or to get rid of something",
    "ditto": "the same as what was said before",
    "ditty": "a short, simple song",
    "dizzy": "having a sensation of spinning and loss of balance",
    "dodge": "to avoid something by a quick movement",
    "dolly": "a child's toy baby, or a platform on wheels",
    "donor": "a person who gives or donates something",
    "donut": "a small, fried, sweet, ring-shaped cake",
    "doubt": "a feeling of uncertainty or lack of conviction",
    "dough": "a thick mixture of flour and liquid used for baking",
    "dowry": "property or money brought by a bride to her husband",
    "dozen": "a group of twelve",
    "draft": "a preliminary version of writing, or a current of air",
    "drain": "to remove liquid from something",
    "drama": "a play for theater, radio, or TV; an exciting event",
    "drank": "past tense of drink",
    "drape": "to arrange cloth or clothing loosely on something",
    "drawl": "to speak slowly with prolonged vowel sounds",
    "dread": "to anticipate with great fear or apprehension",
    "dream": "a series of thoughts and images during sleep; a wish",
    "dress": "a one-piece garment for a woman or girl, or to put on clothes",
    "dried": "past tense of dry; preserved by removing moisture",
    "drift": "to be carried slowly by a current of air or water",
    "drill": "a tool for boring holes, or a training exercise",
    "drink": "to take a liquid into the mouth and swallow it",
    "drive": "to operate a vehicle, or a trip in a car",
    "droit": "a legal right or claim",
    "droll": "curious or unusual in a way that provokes dry amusement",
    "drone": "a continuous low humming sound, or a remote-controlled aircraft",
    "drool": "to let saliva run from the mouth",
    "droop": "to bend or hang downward limply",
    "drops": "plural of drop; small amounts of liquid",
    "drove": "past tense of drive; a large group of animals moving together",
    "drown": "to die from being underwater and unable to breathe",
    "druid": "a priest in ancient Celtic cultures",
    "drunk": "affected by alcohol to the point of loss of control",
    "dryer": "a machine for drying something, especially clothes",
    "dryly": "in a matter-of-fact or ironically humorous way",
    "ducat": "a gold coin used in various European countries",
    "duchy": "the territory of a duke or duchess",
    "ducky": "a child's word for a duck, or something excellent",
    "ducts": "tubes or channels for air, liquid, or cables",
    "dully": "in a manner lacking brightness or interest",
    "dummy": "a model of a human, or a stupid person",
    "dumps": "places where waste is left, or a state of sadness",
    "dunce": "a person who is slow at learning; not intelligent",
    "dunes": "hills of sand formed by wind, often in deserts",
    "dusky": "dark in color; dimly lit like twilight",
    "dusty": "covered with a fine powder of dirt",
    "dutch": "relating to the Netherlands or its people",
    "duvet": "a soft, flat bag filled with down used as a blanket",
    "dwarf": "a being in folklore, short and human-like",
    "dwell": "to live in or at a specified place",
    "dying": "approaching death; ceasing to live",
    "eager": "very interested and excited to do something",
    "eagle": "a large, powerful bird of prey with a hooked beak",
    "early": "happening before the usual or expected time",
    "earth": "the planet we live on; soil or dirt",
    "easel": "a wooden frame to hold an artist's painting",
    "eaten": "past tense of eat; having consumed food",
    "ebony": "a dark black hardwood",
    "echo": "a sound that repeats when it bounces off a surface",
    "eerie": "strange and frightening; spooky",
    "elbow": "the joint in the middle of your arm",
    "elder": "an older person, often one with authority",
    "elect": "to choose someone by voting",
    "elite": "the best or most skilled group of people",
    "elope": "to run away secretly to get married",
    "elves": "plural of elf; mythical, pointy-eared creatures",
    "email": "a message sent electronically over the internet",
    "embed": "to fix something firmly in a surrounding mass",
    "ember": "a small piece of glowing coal or wood in a dying fire",
    "empty": "containing nothing; not filled",
    "enact": "to make a bill or law official",
    "enemy": "a person who is actively opposed or hostile to someone",
    "enjoy": "to take pleasure in something",
    "enter": "to come or go into a place",
    "entry": "a place of entrance; the act of going in",
    "epoch": "a particular period of time in history",
    "equal": "being the same in quantity, size, or value",
    "equip": "to supply with the necessary items for a purpose",
    "erase": "to rub out or remove written marks",
    "erect": "upright; or to build something",
    "erode": "to gradually wear away, like soil by water",
    "error": "a mistake",
    "erupt": "to burst out suddenly, like a volcano",
    "essay": "a short piece of writing on a particular subject",
    "ether": "a substance used as an anesthetic; the clear sky",
    "ethic": "a set of moral principles",
    "event": "a thing that happens, especially an important one",
    "every": "each one of a group, without exception",
    "exact": "precise and accurate; not approximate",
    "excel": "to be exceptionally good at something",
    "exec": "informal for executive; a top-level manager",
    "exert": "to apply or bring to bear (force or influence)",
    "exile": "the state of being barred from one's native country",
    "exist": "to be real or alive",
    "extra": "more than is usual or necessary",
    "exult": "to show or feel triumphant elation",
    "fable": "a short story, typically with animals, that teaches a moral lesson",
    "faced": "past tense of face; confronted or dealt with",
    "facet": "one side or feature of something",
    "faint": "to lose consciousness; barely visible or heard",
    "fairy": "a small, mythical being with magical powers",
    "faith": "complete trust or confidence",
    "false": "not true; incorrect",
    "fancy": "to want something; elaborate or decorative",
    "fangs": "long, sharp teeth",
    "farce": "a ridiculous situation; a comic play",
    "fatal": "causing death",
    "fatty": "containing a lot of fat",
    "fault": "a defect or responsibility for a mistake",
    "fauna": "the animals of a particular region",
    "favor": "an act of kindness; to prefer something",
    "feast": "a large and special meal",
    "fecal": "relating to feces",
    "feign": "to pretend to feel something",
    "fella": "informal for fellow; a man or boy",
    "felon": "a person who has committed a serious crime",
    "fence": "a barrier enclosing an area",
    "feral": "wild, especially after escaping from domestication",
    "ferry": "a boat that transports people or vehicles across water",
    "fetal": "relating to a fetus",
    "fetch": "to go for and bring back something",
    "fever": "an abnormally high body temperature",
    "fewer": "a smaller number of (used with countable things)",
    "fiber": "a thread or filament; dietary material",
    "field": "an open area of land; a particular branch of study",
    "fiend": "an evil spirit; a very enthusiastic fan",
    "fifth": "the position in a sequence corresponding to the number 5",
    "fifty": "the number 50",
    "fight": "to take part in a violent struggle",
    "filer": "a person who files documents",
    "filet": "a boneless piece of meat or fish",
    "filly": "a young female horse",
    "filmy": "thin and translucent",
    "filth": "disgusting dirt",
    "final": "last in a series; the ultimate decision",
    "finch": "a small songbird",
    "finer": "of higher quality (comparative of fine)",
    "first": "coming before all others",
    "fishy": "relating to fish; suspicious",
    "fisty": "inclined to use the fists; ready for a fight",
    "fixed": "fastened securely; repaired",
    "fixer": "a person who makes arrangements or solves problems",
    "fizzy": "effervescent; having bubbles",
    "flack": "criticism; or a publicist",
    "flail": "to wave wildly",
    "flair": "a natural talent or style",
    "flake": "a small, thin piece of something",
    "flame": "a hot, glowing body of ignited gas",
    "flank": "the side of something",
    "flare": "to burn suddenly; a signal light",
    "flash": "a sudden bright light",
    "flask": "a container for liquids",
    "flats": "apartments on one floor; or shoes with no heel",
    "flaws": "imperfections or defects",
    "flees": "runs away from danger",
    "fleet": "a group of ships or vehicles",
    "flesh": "the soft substance of the body",
    "flick": "a quick, light movement",
    "flier": "a person or thing that flies; a pamphlet",
    "flies": "moves through the air; or insects",
    "fling": "to throw forcefully; a short, passionate relationship",
    "flint": "a hard stone used to start fires",
    "flirt": "to behave playfully in a romantic way",
    "float": "to rest on the surface of a liquid",
    "flock": "a group of birds or sheep",
    "flood": "an overflow of water",
    "floor": "the lower surface of a room",
    "flora": "the plants of a particular region",
    "floss": "thread for cleaning between teeth",
    "flour": "powder made from grain, used in baking",
    "flout": "to openly disregard a rule",
    "flown": "past participle of fly; having traveled through air",
    "fluff": "soft, light fibers",
    "fluid": "a substance that flows, like a liquid or gas",
    "fluke": "a lucky stroke",
    "flume": "a narrow gorge with a stream",
    "flung": "past tense of fling; threw forcefully",
    "flunk": "to fail, especially in an exam",
    "flush": "to cleanse with a rapid flow of water; having plenty of money",
    "flute": "a musical wind instrument",
    "flyer": "variant of flier; a pamphlet",
    "foamy": "full of or covered with foam",
    "focal": "relating to a focus; central",
    "focus": "the center of interest or activity",
    "foggy": "full of fog; murky",
    "foist": "to impose an unwelcome thing on someone",
    "foldy": "capable of being folded (informal)",
    "folio": "a sheet of paper folded once",
    "folks": "people in general; one's relatives",
    "folly": "foolishness; a foolish act",
    "foray": "a sudden attack or incursion",
    "force": "strength or power",
    "forge": "to shape metal; to create something strong",
    "forgo": "to go without; to refrain from",
    "forky": "resembling a fork; divided into parts",
    "forma": "shape or arrangement",
    "forte": "a thing at which someone excels",
    "forth": "forward in time or place",
    "forty": "the number 40",
    "forum": "a meeting or medium for discussion",
    "found": "past tense of find; to establish",
    "foyer": "an entrance hall in a building",
    "frail": "weak and delicate",
    "frame": "a rigid structure that surrounds something",
    "frank": "open, honest, and direct",
    "fraud": "wrongful deception for financial gain",
    "freak": "a very unusual event or person",
    "freed": "past tense of free; released",
    "freer": "more free (comparative of free)",
    "fresh": "new; not stale or spoiled",
    "friar": "a member of a religious order",
    "fried": "cooked in hot oil or fat",
    "frill": "a strip of gathered material used as decoration",
    "frisk": "to search a person by running hands over clothes",
    "fritz": "a state of disrepair (on the fritz)",
    "frock": "a dress",
    "frond": "a large, divided leaf, especially of a fern",
    "front": "the forward-facing part",
    "frost": "a thin layer of ice crystals",
    "froth": "a mass of small bubbles; foam",
    "frown": "to furrow one's brow in displeasure",
    "froze": "past tense of freeze; turned to ice",
    "fruit": "the sweet product of a tree or plant",
    "fudge": "a soft, rich candy; to manipulate or adjust",
    "fully": "completely or entirely",
    "fumes": "gas, smoke, or vapor, often unpleasant",
    "funds": "money, especially for a specific purpose",
    "fungi": "plural of fungus; mushrooms, mold, etc.",
    "funky": "having a strong, unpleasant smell; stylish in an unconventional way",
    "funny": "amusing; causing laughter",
    "furor": "an outbreak of public excitement or anger",
    "furry": "covered with fur",
    "fused": "joined or blended together",
    "fussy": "hard to please; paying great attention to detail",
    "fuzzy": "having a frizzy, fluffy, or indistinct texture",
    "gabby": "talkative, prone to chattering",
    "gable": "the triangular part of a wall under a roof",
    "gains": "profits or advantages obtained",
    "gamer": "a person who plays video games",
    "gamma": "the third letter of the Greek alphabet",
    "gamut": "the complete range or scope of something",
    "gassy": "filled with or resembling gas",
    "gaudy": "extravagantly bright or showy",
    "gauge": "an instrument for measuring; to estimate",
    "gaunt": "lean and haggard, especially from hunger or age",
    "gauze": "a thin, transparent fabric",
    "gavel": "a small hammer used by a judge or auctioneer",
    "gawky": "clumsy; awkward in movement",
    "gazer": "a person who stares intently",
    "gecko": "a small tropical lizard",
    "geese": "plural of goose",
    "genie": "a magical spirit from folklore",
    "genre": "a category of artistic composition",
    "ghost": "the spirit of a dead person",
    "ghoul": "an evil spirit that robs graves",
    "giant": "a being of human form but superhuman size",
    "giddy": "dizzy; excitable and frivolous",
    "girly": "characteristic of or suitable for a girl",
    "girth": "the measurement around the middle of something",
    "given": "specified or stated",
    "giver": "a person who gives something",
    "glade": "an open space in a forest",
    "gland": "an organ in the body that secretes substances",
    "glare": "to stare fiercely; a harsh, bright light",
    "glass": "a hard, brittle transparent substance",
    "glaze": "a glossy coating; to fit with glass",
    "gleam": "to shine brightly, especially with reflected light",
    "glean": "to gather information or material bit by bit",
    "glide": "to move smoothly and continuously",
    "glint": "to give out or reflect small flashes of light",
    "gloat": "to dwell on one's own success with smugness",
    "globe": "the earth; a spherical object",
    "gloom": "partial or total darkness; a state of depression",
    "glory": "high renown or honor won by notable achievements",
    "gloss": "shine or luster on a smooth surface",
    "glove": "a covering for the hand",
    "glued": "stuck together with glue",
    "gnarl": "a rough, knotty protuberance on a tree",
    "gnome": "a mythical dwarflike creature",
    "goals": "aims or desired results",
    "goats": "hoofed mammals often kept for milk",
    "godly": "devoutly religious; like a god",
    "going": "the act of leaving; current situation",
    "golem": "a clay figure brought to life in Jewish folklore",
    "golly": "a mild exclamation of surprise",
    "goner": "a person or thing that is doomed",
    "goods": "merchandise or possessions",
    "goody": "something attractive or desirable, especially food",
    "gooey": "soft and sticky",
    "goofy": "silly; foolish",
    "goose": "a waterbird with a long neck",
    "gored": "pierced with a horn or tusk",
    "gorge": "a narrow valley; to eat greedily",
    "gouge": "to make a groove or hole in something",
    "gourd": "a fleshy, typically large fruit with a hard skin",
    "gowns": "long, elegant dresses",
    "grace": "simple elegance or refinement of movement",
    "grade": "a particular level of rank or quality",
    "graft": "to insert a shoot from one plant into another",
    "grail": "something eagerly sought after (like the Holy Grail)",
    "grain": "a small, hard seed of a food plant",
    "grams": "metric units of mass",
    "grand": "magnificent and imposing",
    "grant": "to agree to give or allow",
    "grape": "a small, round fruit that grows in clusters",
    "graph": "a diagram showing the relation between variables",
    "grasp": "to seize and hold firmly; to understand",
    "grass": "a common plant with narrow leaves",
    "grate": "to shred; a metal framework",
    "grave": "a place of burial; serious",
    "gravy": "a sauce made from meat juices",
    "graze": "to eat grass; to scrape lightly",
    "great": "of an extent, amount, or intensity above average",
    "greed": "intense and selfish desire for something",
    "green": "of the color between blue and yellow",
    "greet": "to give a sign of welcome",
    "grief": "deep sorrow, especially caused by someone's death",
    "grill": "a device for cooking food over direct heat",
    "grime": "dirt ingrained on a surface",
    "grind": "to crush into small particles",
    "gripe": "to complain about something in a persistent, irritating way",
    "grits": "a porridge made from ground corn",
    "groan": "a deep sound of pain or despair",
    "groin": "the area between the abdomen and the thigh",
    "groom": "a man on his wedding day; to brush and clean an animal",
    "grope": "to feel about or search blindly",
    "gross": "very unpleasant; total amount before deductions",
    "group": "a number of people or things located close together",
    "grout": "a mortar used to fill gaps between tiles",
    "grove": "a small group of trees",
    "growl": "to make a low guttural sound of hostility",
    "grown": "past participle of grow; having reached maturity",
    "gruel": "a thin liquid food of oatmeal boiled in water",
    "gruff": "abrupt or taciturn in manner",
    "grump": "a grumpy person",
    "grunt": "a low, short guttural sound",
    "guard": "to watch over in order to protect",
    "guava": "a tropical fruit with pink juicy flesh",
    "guess": "to estimate or suppose without sufficient information",
    "guest": "a person who is invited to visit someone's home",
    "guide": "a person who advises or shows the way",
    "guild": "an association of people for mutual aid",
    "guile": "sly or cunning intelligence",
    "guilt": "the fact of having committed a specified offense",
    "guise": "an external form, appearance, or manner",
    "gulch": "a deep, narrow ravine",
    "gully": "a water-worn ravine",
    "gumbo": "a soup or stew thickened with okra",
    "gummy": "having a sticky consistency; resembling gum",
    "guppy": "a small, brightly colored freshwater fish",
    "gushy": "overly demonstrative or emotional",
    "gusto": "vigorous enjoyment or enthusiasm",
    "gusty": "characterized by or blowing in gusts",
    "gutsy": "having or showing courage and determination",
    "habit": "a regular practice or routine",
    "hairy": "covered with hair",
    "halve": "to divide into two equal parts",
    "handy": "useful or convenient",
    "happy": "feeling or showing pleasure",
    "hardy": "robust; capable of enduring hardship",
    "hasty": "done with excessive speed or urgency",
    "hatch": "to emerge from an egg; an opening in a floor",
    "hated": "past tense of hate; felt intense dislike for",
    "haunt": "to visit as a ghost; to frequent a place",
    "haven": "a safe place",
    "havoc": "widespread destruction or chaos",
    "hazel": "a light brown color; a type of tree",
    "heady": "intoxicating; having a strong effect",
    "heaps": "a lot of something",
    "heart": "the organ that pumps blood; emotional center",
    "heath": "an area of open uncultivated land",
    "heave": "to lift or throw something heavy",
    "hedge": "a fence formed by bushes or shrubs",
    "hefty": "large, heavy, and powerful",
    "heist": "a robbery",
    "helix": "a spiral shape, like DNA",
    "hello": "a common greeting",
    "hence": "as a consequence; for this reason",
    "herbs": "plants used for flavoring or medicine",
    "heron": "a long-legged freshwater bird",
    "hilly": "having many hills",
    "hinge": "a movable joint for a door",
    "hippo": "short for hippopotamus",
    "hippy": "a person with unconventional values (also hippie)",
    "hitch": "to connect; a temporary problem",
    "hoard": "a hidden stock or supply",
    "hoary": "grayish-white; old and trite",
    "hobby": "an activity done for pleasure",
    "hocus": "to trick or deceive (as in hocus-pocus)",
    "hoist": "to raise or lift up",
    "holly": "a shrub with red berries and prickly leaves",
    "homer": "a home run in baseball",
    "honed": "sharpened; refined or perfected",
    "honey": "a sweet, sticky substance made by bees",
    "honor": "high respect; integrity",
    "horde": "a large group of people",
    "horny": "having horns; feeling sexual excitement",
    "horse": "a large four-legged animal",
    "hotel": "a place providing lodging for travelers",
    "hotly": "in a passionate or intense manner",
    "hound": "a dog used for hunting; to pursue relentlessly",
    "house": "a building for people to live in",
    "hovel": "a small, squalid, unpleasant dwelling",
    "hover": "to remain in one place in the air",
    "howdy": "an informal greeting (hello)",
    "howls": "makes a long, loud, crying sound",
    "human": "relating to people",
    "humid": "having a lot of moisture in the air",
    "humor": "the quality of being amusing",
    "humph": "an expression of annoyance or doubt",
    "hunch": "a feeling or guess not based on facts",
    "hunky": "physically attractive and well-built",
    "hurry": "to move or act with great speed",
    "husky": "big and strong; a breed of dog",
    "hussy": "a cheeky or improper woman",
    "hutch": "a cage for small animals",
    "hyena": "a dog-like African mammal",
    "hymen": "a membrane at the opening of the vagina",
    "hymns": "religious songs",
    "hyper": "extremely active or energetic",
    "icing": "a sweet glaze for cakes",
    "ideal": "perfect; most suitable",
    "idiom": "a common phrase with a non-literal meaning",
    "idiot": "a stupid person",
    "idler": "a lazy person",
    "idyll": "a happy and peaceful scene",
    "igloo": "a dome-shaped snow house",
    "image": "a picture or representation",
    "imbue": "to inspire or fill with a feeling",
    "impel": "to drive or force to action",
    "imply": "to suggest without stating directly",
    "inane": "silly; stupid",
    "index": "an alphabetical list at the back of a book",
    "inept": "clumsy; unskilled",
    "inert": "unmoving; inactive",
    "infer": "to conclude from evidence",
    "ingot": "a brick of gold or silver",
    "inlet": "a small bay",
    "inner": "inside; internal",
    "input": "what is put in (e.g., data, advice)",
    "inset": "a small picture or map within a larger one",
    "inter": "to bury a dead body",
    "intro": "an introduction",
    "ionic": "relating to ions; a type of chemical bond",
    "irate": "very angry",
    "irony": "when the opposite of what is expected happens",
    "islet": "a very small island",
    "issue": "a topic or problem; to distribute",
    "itchy": "having an irritation that makes you want to scratch",
    "ivory": "hard white material from elephant tusks",
    "jaded": "tired or bored from too much of something",
    "jaunt": "a short, fun trip",
    "jazzy": "bright and colorful; lively",
    "jelly": "a wobbly, fruit-flavored dessert",
    "jerky": "dried, seasoned meat",
    "jetty": "a pier or structure projecting into water",
    "jiffy": "a very short time",
    "jolly": "happy and cheerful",
    "joust": "to fight on horseback with lances",
    "jowls": "the lower part of a person's cheek",
    "judge": "a public official who decides cases in court",
    "juice": "the liquid from fruits or vegetables",
    "jumbo": "very large",
    "jumpy": "nervous; easily startled",
    "junta": "a military group that rules a country",
    "juror": "a member of a jury",
    "kappa": "the tenth letter of the Greek alphabet",
    "karma": "the belief that your actions affect your future",
    "kayak": "a narrow canoe covered with a deck",
    "kebab": "pieces of meat and vegetables grilled on a skewer",
    "khaki": "a dull brownish-yellow color",
    "kinky": "having twists or curls; relating to unusual sexual tastes",
    "kiosk": "a small booth selling newspapers or tickets",
    "kitty": "a pet name for a cat; money pooled together",
    "knack": "a special skill or ability",
    "knave": "a dishonest man",
    "knead": "to work dough with your hands",
    "kneel": "to rest on your knees",
    "knelt": "past tense of kneel",
    "knife": "a tool with a sharp blade for cutting",
    "knock": "to hit a door to gain entry",
    "knoll": "a small, rounded hill",
    "known": "past participle of know; recognized or familiar",
    "koala": "an Australian tree-dwelling marsupial",
    "krill": "tiny shrimp-like sea creatures",
    "kudos": "praise and honor for an achievement",
    "label": "a small tag giving information",
    "labor": "work, especially physical work",
    "laden": "heavily loaded",
    "ladle": "a large spoon for serving soup",
    "lager": "a type of beer",
    "lance": "a long spear",
    "lanky": "tall, thin, and ungraceful",
    "lapel": "the folded flap on the front of a jacket",
    "lapse": "a temporary failure; a slip",
    "large": "big in size or amount",
    "larva": "the juvenile form of an insect",
    "laser": "a device that emits a focused beam of light",
    "lasso": "a rope with a noose for catching cattle",
    "latch": "a fastening for a door or gate",
    "later": "at a time in the future",
    "lathe": "a machine for shaping wood or metal",
    "latte": "a coffee drink with steamed milk",
    "laugh": "to make the sound of amusement",
    "layer": "a sheet or level of material",
    "leach": "to drain away from soil",
    "leafy": "having many leaves",
    "leaky": "having a hole that lets liquid out",
    "leapt": "past tense of leap; jumped",
    "learn": "to gain knowledge or skill",
    "lease": "a contract to rent property",
    "leash": "a strap for controlling an animal",
    "least": "smallest in amount or extent",
    "leave": "to go away from; permission to be absent",
    "ledge": "a narrow shelf",
    "leech": "a parasitic worm; a person who exploits others",
    "leery": "cautious or wary",
    "lefty": "a left-handed person",
    "legal": "related to the law; permitted",
    "lemon": "a yellow, sour citrus fruit",
    "lemur": "a primate from Madagascar",
    "lends": "gives temporarily (third person)",
    "level": "flat and even; a floor of a building",
    "lever": "a bar used to lift something",
    "libel": "a published false statement that damages reputation",
    "liege": "a lord or sovereign",
    "light": "the natural agent that makes things visible",
    "liken": "to point out similarities",
    "lilac": "a shrub with fragrant purple or white flowers",
    "limbo": "a state of neglect or uncertainty",
    "limit": "a point beyond which something does not extend",
    "linen": "a fabric made from flax",
    "liner": "a large passenger ship; an inner coating",
    "lingo": "a foreign language; special vocabulary",
    "links": "connections; a golf course",
    "lipid": "a fatty substance",
    "lithe": "thin, supple, and graceful",
    "liver": "a vital organ in the abdomen",
    "livid": "furiously angry",
    "llama": "a South American animal related to the camel",
    "loamy": "rich, fertile soil",
    "loath": "reluctant; unwilling",
    "lobby": "a room providing a waiting area",
    "local": "relating to a particular area",
    "locke": "a variant of lock; secured",
    "locus": "a particular position or point",
    "lodge": "a small house in the country; to become stuck",
    "lofty": "of imposing height; noble",
    "logic": "reasoning conducted according to strict principles",
    "login": "the process of gaining access to a computer",
    "loopy": "crazy or silly",
    "loose": "not firmly fixed in place",
    "lords": "men of high rank",
    "lorry": "a large truck",
    "loser": "a person who loses a contest",
    "lousy": "very poor or bad",
    "lover": "a person in a romantic relationship",
    "lower": "to move something down",
    "lowly": "low in status",
    "loyal": "faithful to a person or cause",
    "lucid": "clear and understandable",
    "lucky": "having good luck",
    "lumen": "a unit of light flow",
    "lumpy": "full of lumps",
    "lunar": "relating to the moon",
    "lunch": "a meal eaten in the middle of the day",
    "lunge": "a sudden forward movement",
    "lupus": "an autoimmune disease",
    "lurch": "a sudden unsteady movement",
    "lured": "past tense of lure; tempted",
    "lurid": "unpleasantly bright in color; shocking",
    "lusty": "healthy and strong; full of vigor",
    "lying": "present participle of lie; being untruthful",
    "lymph": "a colorless fluid in the body",
    "lynch": "to kill someone by mob action without a legal trial",
    "lyric": "the words of a song",
    "macaw": "a large, colorful parrot",
    "macho": "aggressively masculine",
    "macro": "large-scale; a single computer instruction",
    "madam": "a polite form of address for a woman",
    "madly": "in a wild or frantic way",
    "mafia": "an organized crime syndicate",
    "magic": "the power of apparently influencing events by mystery",
    "magma": "hot fluid under the earth's crust",
    "maize": "a type of corn",
    "major": "important, serious, or significant",
    "maker": "a person or thing that makes something",
    "mambo": "a Latin American dance",
    "mamma": "mother (informal)",
    "manga": "Japanese comic books",
    "mange": "a skin disease in animals",
    "mango": "a tropical fruit",
    "mangy": "having mange; shabby",
    "mania": "an excessive enthusiasm or desire",
    "manic": "showing wild and apparently deranged excitement",
    "manly": "having qualities associated with men",
    "manna": "food from heaven",
    "manor": "a large country house with lands",
    "maple": "a type of tree; source of syrup",
    "march": "to walk in a military manner; the third month",
    "marry": "to become spouses",
    "marsh": "an area of low-lying wet land",
    "mason": "a builder who works with stone",
    "match": "a contest; a small stick for lighting fire",
    "matey": "friendly (informal British)",
    "maths": "mathematics (British)",
    "matte": "a dull, non-glossy finish",
    "mauve": "a pale purple color",
    "maxim": "a short statement of a general truth",
    "maybe": "perhaps; possibly",
    "mayor": "the elected head of a city",
    "mealy": "having a soft, dry, crumbly texture",
    "means": "a method for achieving something; wealth",
    "meant": "past tense of mean; intended",
    "meaty": "full of substance; like meat",
    "mecca": "a place that attracts many people",
    "medal": "a metal disc awarded as a prize",
    "media": "the main means of mass communication",
    "medic": "a medical professional",
    "melee": "a confused fight or scuffle",
    "melon": "a large, juicy fruit",
    "melt": "to turn from solid to liquid",
    "mercy": "compassion or forgiveness",
    "merge": "to combine or blend together",
    "merit": "the quality of being good",
    "merry": "cheerful and lively",
    "messy": "untidy or dirty",
    "metal": "a solid material like iron or gold",
    "meter": "a unit of length; a measuring device",
    "metro": "an urban subway system",
    "micro": "very small",
    "midge": "a small flying insect",
    "midst": "the middle point",
    "might": "great power; past of may",
    "miler": "a runner who specializes in the mile",
    "milky": "resembling milk; white and cloudy",
    "mimic": "to imitate",
    "mince": "to chop into small pieces",
    "miner": "a person who works in a mine",
    "mini": "very small of its kind",
    "minor": "lesser in importance",
    "minty": "tasting or smelling of mint",
    "minus": "reduced by; the subtraction sign",
    "mirth": "amusement, especially as expressed in laughter",
    "miser": "a person who hoards wealth",
    "missy": "a young girl (sometimes condescending)",
    "misty": "full of mist; hazy",
    "mixed": "combined from different elements",
    "mixer": "a machine for mixing things",
    "model": "a representation; a person who poses",
    "modem": "a device for connecting to the internet",
    "moist": "slightly wet",
    "molar": "a back tooth",
    "moldy": "covered with mold",
    "money": "a medium of exchange",
    "month": "one of the twelve periods in a year",
    "moody": "given to changes in mood",
    "moose": "a large deer-like animal",
    "moped": "a small motorcycle",
    "moral": "concerned with principles of right and wrong",
    "moron": "a stupid person",
    "morph": "to change shape smoothly",
    "mossy": "covered in moss",
    "motel": "a hotel for motorists",
    "motif": "a decorative design or theme",
    "motor": "a machine that supplies power",
    "motto": "a short statement expressing a rule",
    "mould": "a furry growth of fungus (UK spelling of mold)",
    "mound": "a small hill",
    "mount": "to climb up; a mountain",
    "mourn": "to feel deep sorrow",
    "mouse": "a small rodent; a computer device",
    "mouth": "the opening in the face for eating and speaking",
    "moved": "past tense of move; changed position",
    "mover": "a person or company that moves belongings",
    "movie": "a motion picture; a film",
    "mower": "a machine for cutting grass",
    "mucky": "dirty; muddy",
    "mucus": "a slimy substance produced by the body",
    "muddy": "covered in or full of mud",
    "mulch": "a material spread around plants for protection",
    "mummy": "a preserved dead body; a mother (British)",
    "munch": "to chew steadily",
    "mural": "a painting on a wall",
    "murky": "dark and gloomy; unclear",
    "mushy": "soft and pulpy; overly sentimental",
    "music": "vocal or instrumental sounds",
    "musky": "having a strong, earthy smell",
    "musty": "having a stale, damp smell",
    "muted": "quiet; not loud",
    "myrrh": "a fragrant resin used in perfume",
    "nadir": "the lowest point",
    "naive": "lacking experience or judgment",
    "naked": "without clothes",
    "named": "past tense of name; given a title",
    "nanny": "a person employed to care for children",
    "nasal": "relating to the nose",
    "nasty": "very bad or unpleasant",
    "natal": "relating to birth",
    "naval": "relating to a navy or ships",
    "navel": "the belly button",
    "needs": "requires; necessities",
    "needy": "poor; lacking basic necessities",
    "nerdy": "socially awkward and interested in niche subjects",
    "nerve": "a fiber that carries impulses in the body; boldness",
    "never": "at no time; not ever",
    "newer": "more recent (comparative of new)",
    "newly": "recently; lately",
    "nicer": "more pleasant (comparative of nice)",
    "niche": "a specialized segment of the market",
    "niece": "a daughter of one's sibling",
    "night": "the period of darkness in each 24 hours",
    "ninja": "a person skilled in ninjutsu",
    "ninth": "the position in a sequence corresponding to the number 9",
    "noble": "belonging to a high social class; having fine qualities",
    "noise": "a sound, especially a loud one",
    "noisy": "making a lot of noise",
    "nomad": "a person who moves from place to place",
    "noose": "a loop with a running knot used for hanging",
    "north": "the direction to your left when facing the rising sun",
    "nosey": "inquisitive about others' affairs (also nosy)",
    "notch": "a V-shaped cut or indentation",
    "noted": "well-known; recorded",
    "novel": "a long written story; new and original",
    "nudge": "to push gently",
    "nurse": "a person trained to care for the sick",
    "nutty": "tasting like nuts; crazy",
    "occur": "to happen",
    "ocean": "a very large expanse of sea",
    "offer": "to present something for acceptance",
    "often": "frequently",
    "olive": "a small green or black fruit",
    "onion": "a pungent edible vegetable",
    "opera": "a dramatic work set to music",
    "orbit": "the path of one object around another",
    "other": "a different person or thing",
    "ought": "used to indicate duty or correctness",
    "ounce": "a unit of weight",
    "outer": "situated on the outside",
    "owner": "a person who owns something",
    "paint": "to apply color to a surface",
    "panel": "a flat section of a surface, or a group of experts",
    "panic": "a sudden feeling of overwhelming fear",
    "paper": "a material for writing, printing, or wrapping",
    "party": "a social gathering, or a political group",
    "pasta": "an Italian food made from flour and water",
    "patch": "a piece of material used to mend a hole",
    "peace": "freedom from disturbance; tranquility",
    "peach": "a soft, juicy fruit with a fuzzy skin",
    "pearl": "a hard, shiny object produced by some oysters",
    "phase": "a distinct stage in a process",
    "phone": "a device for speaking to someone at a distance",
    "piano": "a large musical instrument with a keyboard",
    "piece": "a part of a whole",
    "pilot": "a person who operates an aircraft",
    "pitch": "to throw, or the highness/lowness of a sound",
    "pizza": "an Italian dish of dough topped with cheese and other ingredients",
    "place": "a particular position or location",
    "plane": "an airplane, or a flat surface",
    "plant": "a living organism that grows in the ground",
    "plate": "a flat dish for serving food",
    "plums": "soft, sweet fruits with a stone inside",
    "point": "a specific location, or to indicate direction",
    "porch": "a covered shelter at the entrance of a building",
    "pound": "a unit of weight, or to hit heavily",
    "power": "the ability to do something or act in a particular way",
    "press": "to push firmly, or news media collectively",
    "price": "the amount of money required to buy something",
    "pride": "a feeling of deep pleasure from one's own achievements",
    "prize": "something given as a reward for victory or superiority",
    "proof": "evidence establishing a fact or truth",
    "proud": "feeling deep pleasure or satisfaction",
    "queen": "a female ruler of a country, or the wife of a king",
    "query": "a question, especially one addressed to an official or organization",
    "quest": "a long or arduous search for something",
    "queue": "a line or sequence of people or vehicles awaiting their turn",
    "quick": "moving fast or doing something in a short time",
    "quiet": "making little or no noise",
    "quilt": "a warm bed covering made of padding enclosed between layers of fabric",
    "quirk": "a peculiar behavioral habit",
    "quite": "to the utmost or most absolute extent or degree; absolutely",
    "radio": "a device for receiving broadcast signals",
    "raise": "to lift something up",
    "rally": "to come together for a common purpose",
    "ranch": "a large farm for raising animals",
    "range": "a variety of different things or a line of mountains",
    "rapid": "very fast; quick",
    "ratio": "the relationship between two amounts",
    "reach": "to arrive at a place or extend to a point",
    "react": "to respond to something",
    "ready": "prepared for an activity or situation",
    "realm": "a kingdom or field of interest",
    "rebel": "a person who resists authority",
    "refer": "to mention or direct to a source",
    "relax": "to rest and become less tense",
    "relay": "to receive and pass on information",
    "renal": "relating to the kidneys",
    "renew": "to begin again or extend a contract",
    "repay": "to pay back money",
    "reply": "to answer",
    "rider": "a person who rides an animal or vehicle",
    "ridge": "a long, narrow hilltop or mountain range",
    "rifle": "a long gun with a spirally grooved barrel",
    "right": "correct or a direction opposite of left",
    "rigid": "stiff and not flexible",
    "rival": "a person or group competing with another",
    "river": "a large natural stream of water",
    "roast": "to cook with dry heat in an oven",
    "robot": "a machine capable of carrying out actions automatically",
    "rocky": "full of rocks or unsteady",
    "royal": "relating to a king or queen",
    "sadly": "in a sad manner; unfortunately",
    "salad": "a dish of mixed raw vegetables",
    "salon": "a place where hairdressers or beauticians work",
    "salsa": "a type of sauce or a style of music and dance",
    "salty": "tasting of or containing salt",
    "sandy": "covered with or consisting of sand",
    "sauce": "a liquid substance served with food to add flavor",
    "sauna": "a small room used as a hot-air or steam bath",
    "scale": "a range of values or a device for weighing",
    "scare": "to cause great fear or nervousness",
    "scene": "the place where an incident occurred or a part of a play",
    "scent": "a distinctive smell, especially a pleasant one",
    "scope": "the extent of a subject or area",
    "score": "the number of points in a game or to achieve something",
    "scout": "a person sent out to obtain information",
    "scrap": "a small piece or amount of something; to discard",
    "screw": "a type of metal fastener",
    "seize": "to take hold of suddenly and forcibly",
    "sense": "a faculty by which the body perceives an external stimulus",
    "serum": "the clear, pale yellow liquid part of blood",
    "serve": "to perform duties or services for another person or an organization",
    "setup": "the way in which something is organized or arranged",
    "seven": "the number equivalent to the sum of three and four",
    "shade": "comparative darkness and coolness caused by shelter from direct sunlight",
    "shake": "to move quickly up and down or side to side",
    "shame": "a painful feeling of humiliation or distress",
    "shape": "the external form or appearance of someone or something",
    "share": "to have a portion of something with another or others",
    "sharp": "having a fine edge or point capable of cutting",
    "sheep": "a farm animal kept for its wool and meat",
    "sheer": "nothing other than; complete",
    "sheet": "a large rectangular piece of cloth used on a bed",
    "shelf": "a flat length of wood fixed horizontally for holding objects",
    "shell": "the hard protective outer case of an animal or object",
    "shift": "to move or change from one position or direction to another",
    "shine": "to give out a bright light",
    "shiny": "reflecting light because of a smooth surface",
    "shirt": "a garment for the upper body with sleeves",
    "shock": "a sudden upsetting or surprising event",
    "shoot": "to fire a weapon or to take a photograph",
    "shore": "the land along the edge of a sea or lake",
    "short": "small in length, distance, or height",
    "shout": "to call or cry out loudly",
    "showy": "attracting a lot of attention by being very colorful or bright",
    "sight": "the ability to see or something that is seen",
    "silly": "lacking common sense or judgment; foolish",
    "since": "in the period between a past time and the present",
    "sixth": "constituting number six in a sequence",
    "skill": "the ability to do something well",
    "skirt": "a woman's garment that hangs from the waist",
    "skull": "the bony framework of the head",
    "slate": "a fine-grained gray rock that splits into thin layers",
    "slave": "a person who is the legal property of another",
    "sleep": "a natural state of rest for the body and mind",
    "slice": "a thin, broad piece of food cut from a larger portion",
    "slide": "to move smoothly along a surface",
    "slope": "a surface of which one end or side is higher than another",
    "small": "little in size, amount, or degree",
    "smart": "intelligent or stylish in appearance",
    "smell": "the faculty of perceiving odors",
    "smile": "a pleased, kind, or amused facial expression",
    "smoke": "a visible suspension of carbon in the air from burning",
    "snack": "a small amount of food eaten between meals",
    "snake": "a long, legless reptile",
    "sneak": "to move or go in a furtive or stealthy way",
    "snowy": "covered with snow",
    "soapy": "containing or covered with soap",
    "soccer": "a game played with a round ball between two teams",
    "social": "relating to society or its organization",
    "socks": "garments for the feet and lower legs",
    "solar": "relating to the sun",
    "solid": "firm and stable in shape; not liquid or fluid",
    "solve": "to find an answer to a problem",
    "sorry": "feeling regret or pity",
    "sound": "vibrations that travel through the air and can be heard",
    "south": "the direction toward the south pole",
    "space": "a continuous, unoccupied area",
    "spare": "additional to what is required for ordinary use",
    "spark": "a small fiery particle thrown from a fire",
    "speak": "to say something in order to convey information",
    "speed": "the rate at which someone or something moves",
    "spend": "to give money to pay for goods or services",
    "spice": "a substance used to flavor food",
    "spill": "to cause or allow to run over the edge of a container",
    "spine": "the backbone",
    "spite": "a desire to hurt, annoy, or offend someone",
    "split": "to break or cause to break forcibly into parts",
    "spoon": "an implement for eating, stirring, and serving food",
    "sport": "an activity involving physical exertion and skill",
    "spray": "liquid sent through the air in tiny drops",
    "squad": "a small group of people with a shared task",
    "stack": "a pile of objects, typically neatly arranged",
    "staff": "the employees of an organization",
    "stage": "a point, period, or step in a process",
    "stain": "a discoloration on a surface",
    "stair": "a step in a staircase",
    "stake": "a strong wooden or metal post",
    "stamp": "to bring down one's foot heavily on the ground",
    "stand": "to be in or rise to an upright position",
    "stare": "to look fixedly at someone or something",
    "start": "to begin to do something",
    "state": "the particular condition of someone or something",
    "steak": "a slice of meat or fish, typically beef, cooked by grilling or frying",
    "steal": "to take another person's property without permission",
    "steam": "the vapor into which water is converted when heated",
    "steel": "a hard, strong metal made of iron and carbon",
    "steep": "rising or falling sharply",
    "steer": "to guide the course of a vehicle",
    "stick": "a thin piece of wood or to adhere to a surface",
    "stiff": "not easily bent or changed in shape",
    "still": "not moving or making a sound",
    "stock": "a supply of goods or the shares of a company",
    "stone": "hard, solid non-metallic mineral matter",
    "stool": "a seat without a back or arms",
    "store": "a place where goods are sold",
    "storm": "a violent disturbance of the atmosphere",
    "story": "an account of imaginary or real people and events",
    "stove": "an appliance used for cooking",
    "strap": "a strip of flexible material used for fastening or carrying",
    "straw": "dried stalks of grain or a thin tube for drinking",
    "strip": "to remove a covering or take off clothes",
    "stuck": "unable to move or to be set in a particular position",
    "study": "to devote time and attention to acquiring knowledge",
    "stuff": "matter, material, or things",
    "style": "a particular manner or way of doing something",
    "sugar": "a sweet crystalline substance",
    "suite": "a set of rooms or a set of matching furniture",
    "sunny": "bright with sunlight",
    "super": "very good or excellent",
    "surge": "a sudden powerful forward or upward movement",
    "sushi": "a Japanese dish of rice and seafood",
    "swear": "to make a solemn statement or promise",
    "sweat": "moisture exuded through the pores of the skin",
    "sweep": "to clean an area by brushing away dirt",
    "sweet": "having the pleasant taste of sugar",
    "swell": "to become larger or rounder in size",
    "swift": "happening quickly or promptly",
    "swing": "to move back and forth",
    "sword": "a weapon with a long metal blade",
    "table": "a piece of furniture with a flat top and one or more legs",
    "taste": "the sensation of flavor perceived in the mouth",
    "teach": "to impart knowledge or skill to someone",
    "thank": "to express gratitude to someone",
    "their": "belonging to or associated with the people or things previously mentioned",
    "theme": "the subject of a talk, piece of writing, or exhibition",
    "there": "in, at, or to that place or position",
    "these": "plural of 'this'",
    "thick": "with opposite sides or surfaces relatively far apart",
    "thing": "an object, item, or matter that is not specifically named",
    "think": "to have a particular opinion, belief, or idea",
    "third": "constituting number three in a sequence",
    "those": "plural of 'that'",
    "three": "equivalent to the sum of one and two",
    "throw": "to propel something through the air with a motion of the arm",
    "thumb": "the short, thick first digit of the human hand",
    "tiger": "a large wild cat with a yellow-orange coat with black stripes",
    "tight": "fixed, fastened, or closed firmly; hard to move or undo",
    "timer": "a device that measures or signals the end of a time interval",
    "tired": "in need of sleep or rest; weary",
    "title": "the name of a book, composition, or other artistic work",
    "today": "on or in the course of this present day",
    "toast": "sliced bread browned on both sides by exposure to heat",
    "token": "a thing serving as a visible representation of a fact or quality",
    "tonne": "a metric unit of mass equal to 1,000 kilograms",
    "tooth": "each of a set of hard, bony enamel-coated structures in the jaws",
    "topic": "a matter dealt with in a text, discourse, or conversation",
    "total": "comprising the whole number or amount",
    "touch": "to come into or be in contact with",
    "tough": "strong enough to withstand adverse conditions or rough handling",
    "tower": "a tall, narrow building, either free-standing or forming part of a castle",
    "trace": "to find or discover by investigation",
    "track": "a rough path or road, typically one beaten by use rather than constructed",
    "trade": "the action of buying and selling goods and services",
    "train": "a series of railroad cars moved as a unit by a locomotive",
    "trash": "discarded matter; refuse",
    "treat": "to behave toward or deal with in a certain way",
    "trend": "a general direction in which something is developing or changing",
    "trial": "a formal examination of evidence by a judge",
    "tribe": "a social division in a traditional society",
    "trick": "a cunning or skillful act or scheme intended to deceive",
    "tried": "past tense of try; tested and proven good or trustworthy",
    "trip": "a journey or excursion, especially for pleasure",
    "truly": "in a truthful way; honestly",
    "trust": "firm belief in the reliability, truth, or ability of someone or something",
    "truth": "the quality or state of being true",
    "tutor": "a private teacher, typically one who teaches a single student",
    "twice": "two times; on two occasions",
    "twist": "to form into a bent, curling, or distorted shape",
    "ultra": "an extremist; beyond the usual limit",
    "uncle": "the brother of one's father or mother or the husband of one's aunt",
    "under": "extending or directly below something",
    "undue": "unwarranted or inappropriate because excessive or disproportionate",
    "union": "the action or fact of joining or being joined",
    "unite": "to come or bring together for a common purpose or action",
    "unity": "the state of being united or joined as a whole",
    "until": "up to the point in time or the event mentioned",
    "upper": "situated above another part",
    "upset": "to make someone unhappy, disappointed, or worried",
    "urban": "relating to a city or town",
    "urged": "past tense of urge; to strongly encourage someone to do something",
    "usage": "the action of using something or the fact of being used",
    "usher": "a person who shows people to their seats",
    "using": "present participle of use; employing for a purpose",
    "usual": "habitually or typically occurring or done; customary",
    "vague": "of uncertain or indefinite character or meaning",
    "valid": "having a sound basis in logic or fact; reasonable",
    "value": "the regard that something is held to deserve; importance",
    "valve": "a device for controlling the passage of fluid through a pipe",
    "van": "a medium-sized motor vehicle for transporting goods or people",
    "vary": "to differ in size, amount, degree, or nature from something else",
    "vast": "of very great extent or quantity; immense",
    "venue": "the place where an event or activity is held",
    "verse": "writing arranged with a metrical rhythm, typically having a rhyme",
    "video": "the recording or broadcasting of visual images",
    "view": "the ability to see something or to be seen from a particular place",
    "viral": "relating to or involving an image or piece of information circulated rapidly online",
    "visit": "to go to see and spend time with someone socially",
    "vital": "absolutely necessary or important; essential",
    "vivid": "producing powerful feelings or strong, clear images in the mind",
    "vocal": "relating to the human voice",
    "voice": "the sound produced in a person's larynx and uttered through the mouth",
    "volume": "the amount of space that a substance or object occupies",
    "vote": "a formal expression of opinion or choice",
    "wages": "a fixed regular payment earned for work or services",
    "waist": "the part of the human body below the ribs and above the hips",
    "waste": "to use or expend carelessly or thoughtlessly",
    "watch": "to look at or observe attentively over a period of time",
    "water": "a transparent fluid which forms the world's streams, lakes, and oceans",
    "weigh": "to find out how heavy someone or something is",
    "weird": "suggesting something supernatural; uncanny",
    "whale": "a very large marine mammal with a streamlined body",
    "wheat": "a cereal plant that is the most important kind grown in temperate countries",
    "wheel": "a circular object that revolves on an axle and is fixed below a vehicle",
    "where": "in or to what place or position",
    "which": "asking for information specifying one or more people or things from a definite set",
    "while": "a period of time",
    "white": "of the color of milk or fresh snow",
    "whole": "all of; entire",
    "whose": "belonging to or associated with which person",
    "width": "the measurement or extent of something from side to side",
    "woman": "an adult human female",
    "women": "plural of woman",
    "world": "the earth, together with all of its countries and peoples",
    "worry": "to feel or cause to feel anxious or troubled about actual or potential problems",
    "worse": "of poorer quality or lower standard; less good or desirable",
    "worst": "of the poorest quality or the lowest standard",
    "worth": "equivalent in value to the sum or item specified",
    "would": "past of 'will', used to talk about the future in the past",
    "wound": "an injury to living tissue caused by a cut or blow",
    "write": "to mark letters, words, or other symbols on a surface",
    "wrong": "not correct or true; incorrect",
    "xenon": "a heavy, colorless, odorless noble gas used in lights",
    "xerox": "a copy of a document made by a photocopier (often capitalized)",
    "xylem": "the vascular tissue in plants that conducts water and nutrients",
    "yacht": "a medium-sized sailing boat equipped for cruising or racing",
    "yearn": "to have an intense feeling of longing for something",
    "yeast": "a fungus used in brewing and baking to cause fermentation",
    "yield": "to produce or provide; to give way under pressure",
    "youth": "the period between childhood and adult age",
    "zebra": "an African wild horse with black-and-white stripes",
    "zesty": "having a strong, pleasant, and somewhat spicy flavor or quality",
    "zippy": "bright, fresh, or lively",
    "zonal": "relating to or arranged in zones",
    "zoned": "divided or designated by zones",
    "zones": "areas distinguished from surrounding parts by a particular feature",
    "zooms": "moves or travels very quickly",
}
fives_list = fives_json.keys()
