fours_json = {
    "able": "having the power, skill, means, or opportunity to do something",
    "ache": "a continuous or prolonged dull pain in a part of the body",
    "acid": "a chemical substance that neutralizes alkalis, dissolves some metals, and turns litmus red",
    "acne": "a skin condition characterized by red pimples on the skin",
    "acre": "a unit of land area equal to 4,840 square yards",
    "aged": "having lived for a long time; old",
    "aide": "an assistant to an important person",
    "aims": "points or directs (a weapon or camera) at a target",
    "airy": "spacious, well lit, and well ventilated",
    "akin": "of similar character; similar in nature",
    "ally": "a state formally cooperating with another for a military purpose",
    "also": "in addition; too",
    "alto": "the second highest singing voice",
    "amid": "surrounded by; in the middle of",
    "ants": "small insects, typically having a sting and living in complex social colonies",
    "arch": "a curved symmetrical structure spanning an opening",
    "area": "a region or part of a town, a country, or the world",
    "arid": "having little or no rain; too dry or barren to support vegetation",
    "arms": "the upper limbs of the human body from the shoulder to the hand",
    "army": "an organized military force equipped for fighting on land",
    "arts": "the expression or application of human creative skill and imagination",
    "atom": "the smallest particle of a chemical element",
    "away": "to or at a distance from a particular place, person, or thing",
    "axes": "plural of axis; imaginary lines about which a body rotates",
    "axis": "an imaginary line about which a body rotates",
    "baby": "a very young child, especially one newly or recently born",
    "back": "the rear surface of the human body from the shoulders to the hips",
    "bail": "the temporary release of an accused person awaiting trial",
    "bald": "having a scalp wholly or partly lacking hair",
    "ball": "a solid or hollow sphere, especially one that is kicked, thrown, or hit in a game",
    "band": "a flat, thin strip or loop of material used for fastening, encircling, or binding",
    "bank": "a financial establishment that invests money deposited by customers",
    "bare": "naked; without the usual covering or protection",
    "bark": "the sharp explosive cry of a dog, fox, or seal",
    "barn": "a large farm building used for storing grain, hay, or straw",
    "base": "the lowest part or edge of something, especially the part on which it rests",
    "bath": "an act of washing oneself in a bath",
    "beam": "a long piece of timber or metal used as a structural support",
    "bean": "an edible seed, typically kidney-shaped",
    "bear": "a large, heavy mammal with thick fur and a very short tail",
    "beat": "strike (a person or an animal) repeatedly and violently",
    "been": "past participle of be",
    "bell": "a hollow metal device that makes a ringing sound when struck",
    "belt": "a strip of leather or other material worn around the waist",
    "bend": "shape or force (something straight) into a curve or angle",
    "bent": "sharply curved or having an angle",
    "best": "of the most excellent, effective, or desirable type or quality",
    "bias": "prejudice in favor of or against one thing compared with another",
    "bike": "a bicycle or motorcycle",
    "bill": "an amount of money owed for goods supplied or services rendered",
    "bind": "tie or fasten (something) tightly",
    "bird": "a warm-blooded egg-laying vertebrate distinguished by feathers and wings",
    "bite": "use the teeth to cut into or through something",
    "blow": "move creating an air current",
    "blue": "of a color intermediate between green and violet",
    "boat": "a small vessel propelled on water by oars, sails, or an engine",
    "body": "the physical structure of a person or an animal",
    "boil": "reach or cause to reach the temperature at which it bubbles and turns to vapor",
    "bold": "showing an ability to take risks; confident and courageous",
    "bomb": "a container filled with explosive or incendiary material",
    "bond": "a thing used to tie something or to fasten things together",
    "bone": "any of the pieces of hard, whitish tissue making up the skeleton",
    "book": "a written or printed work consisting of pages glued or sewn together",
    "boom": "a loud, deep, resonant sound",
    "boot": "a sturdy item of footwear covering the foot and ankle",
    "bore": "make a hole in (something) with a tool or by digging",
    "born": "existing as a result of birth",
    "boss": "a person in charge of a worker or organization",
    "both": "used to refer to two people or things, regarded and identified together",
    "bowl": "a round, deep dish or basin used for food or liquid",
    "bulk": "the mass or magnitude of something large",
    "bump": "knock or run into someone or something with force",
    "burn": "flame or glow while consuming a material such as coal or wood",
    "bush": "a woody plant which is smaller than a tree",
    "busy": "having a great deal to do",
    "byte": "a group of binary digits or bits operated on as a unit",
    "cage": "a structure of bars or wires in which birds or other animals are confined",
    "cake": "an item of soft, sweet food made from a mixture of flour, shortening, eggs, sugar",
    "call": "cry out to (someone) in order to summon them or attract their attention",
    "calm": "not showing or feeling nervousness, anger, or other emotions",
    "came": "past tense of come",
    "camp": "a place with temporary accommodations of huts, tents, or other structures",
    "cane": "the hollow jointed stem of a tall grass, especially bamboo or sugar cane",
    "cape": "a sleeveless cloak, typically a short one",
    "card": "a piece of thick, stiff paper or thin pasteboard",
    "care": "the provision of what is necessary for the health and protection of someone",
    "cart": "a vehicle with two or four wheels pulled by a horse",
    "case": "an instance of a particular situation; an example of something occurring",
    "cash": "money in coins or notes, as distinct from checks, money orders, or credit",
    "cast": "throw (something) forcefully in a specified direction",
    "cats": "plural of cat; small domesticated carnivorous mammals",
    "cave": "a large underground chamber, typically of natural origin",
    "cell": "the smallest structural and functional unit of an organism",
    "chef": "a professional cook, typically the chief cook in a restaurant",
    "chin": "the protruding part of the face below the mouth",
    "chip": "a small piece of something removed in the course of chopping, cutting, or breaking",
    "cite": "quote (a passage, book, or author) as evidence for or justification of an argument",
    "city": "a large town",
    "clam": "a marine bivalve mollusk with shells of equal size",
    "clan": "a social group of families, especially in the Scottish Highlands",
    "clay": "a stiff, sticky fine-grained earth, typically yellow, red, or bluish-gray",
    "clip": "fasten or be fastened with a clip or clips",
    "club": "an association or organization dedicated to a particular interest or activity",
    "coal": "a combustible black or dark brown rock consisting mainly of carbonized plant matter",
    "coat": "an outer garment worn outdoors, having sleeves and typically extending below the hips",
    "code": "a system of words, letters, figures, or other symbols substituted for other words",
    "coin": "a flat, typically round piece of metal with an official stamp",
    "cold": "of or at a low or relatively low temperature",
    "come": "move or travel toward or into a place thought of as near or familiar",
    "cone": "a solid or hollow object which tapers from a circular base to a point",
    "cook": "prepare (food, a dish, or a meal) by combining and heating the ingredients",
    "cool": "of or at a fairly low temperature",
    "copy": "a thing made to be similar or identical to another",
    "core": "the tough central part of various fruits, containing the seeds",
    "corn": "a North American cereal plant that yields large grains set in rows on a cob",
    "cost": "require the payment of (a specified sum of money) before it can be acquired",
    "coup": "a sudden, violent, and illegal seizure of power from a government",
    "crew": "a group of people who work on and operate a ship, boat, aircraft, spacecraft",
    "crop": "a cultivated plant that is grown as food, especially a grain, fruit, or vegetable",
    "crow": "a large perching bird with mostly glossy black plumage",
    "cube": "a symmetrical three-dimensional shape, either solid or hollow",
    "cult": "a system of religious veneration and devotion directed toward a particular figure",
    "cure": "relieve (a person or animal) of the symptoms of a disease or condition",
    "curl": "form or cause to form into a curved or spiral shape",
    "cute": "attractive in a pretty or endearing way",
    "dame": "a woman of rank, station, or authority",
    "damp": "slightly wet",
    "dare": "have the courage to do something",
    "dark": "with little or no light",
    "dart": "a small pointed missile used as a weapon or in the game of darts",
    "data": "facts and statistics collected together for reference or analysis",
    "date": "the day of the month or year as specified by a number",
    "dawn": "the first appearance of light in the sky before sunrise",
    "days": "plural of day; each of the twenty-four-hour periods",
    "dead": "no longer alive",
    "deaf": "lacking the power of hearing or having impaired hearing",
    "deal": "distribute (cards) in an orderly rotation to the players for a game or round",
    "dear": "regarded with deep affection; cherished by someone",
    "debt": "a sum of money that is owed or due",
    "deck": "a structure of planks or plates forming the floor of a ship",
    "deep": "extending far down from the top or surface",
    "deer": "a hoofed grazing or browsing animal, with branched bony antlers",
    "deny": "state that one refuses to admit the truth or existence of",
    "desk": "a piece of furniture with a flat or sloped surface for writing",
    "dice": "small cubes with each side having a different number of spots",
    "died": "past tense of die; stopped living",
    "diet": "the kinds of food that a person, animal, or community habitually eats",
    "dime": "a ten-cent coin",
    "dire": "extremely serious or urgent",
    "dirt": "a substance, such as mud or dust, that soils someone or something",
    "dish": "a shallow, typically flat-bottomed container for cooking or serving food",
    "dive": "plunge head first into water",
    "dock": "an enclosed area of water in a port for the loading and repair of ships",
    "does": "third person singular present of do",
    "dome": "a rounded vault forming the roof of a structure",
    "done": "past participle of do",
    "door": "a hinged, sliding, or revolving barrier at the entrance to a building",
    "dose": "a quantity of a medicine or drug taken or recommended to be taken at a particular time",
    "dove": "a stocky seed- or fruit-eating bird with a small head",
    "down": "toward or in a lower place or position",
    "doze": "sleep lightly",
    "drag": "pull (someone or something) along forcefully, roughly, or against their will",
    "draw": "produce (a picture or diagram) by making lines and marks on paper",
    "drew": "past tense of draw",
    "drip": "let fall or be so wet as to shed small drops of liquid",
    "drop": "let or make (something) fall vertically",
    "drug": "a medicine or other substance which has a physiological effect",
    "drum": "a percussion instrument sounded by being struck with sticks or the hands",
    "dual": "consisting of two parts, elements, or aspects",
    "duck": "a waterbird with a broad blunt bill, short legs, webbed feet",
    "dude": "a man; a guy (informal)",
    "dull": "lacking brightness, vividness, or sheen",
    "dune": "a mound or ridge of sand or other loose sediment",
    "dusk": "the darker stage of twilight",
    "dust": "fine particles of matter",
    "duty": "a moral or legal obligation; a responsibility",
    "each": "used to refer to every one of two or more people or things",
    "earl": "a British nobleman ranking above a viscount and below a marquess",
    "earn": "obtain (money) in return for labor or services",
    "ears": "plural of ear; the organs of hearing and balance in humans and other vertebrates",
    "east": "the direction toward the point of the horizon where the sun rises",
    "easy": "achieved with ease; presenting few difficulties",
    "echo": "a sound or series of sounds caused by the reflection of sound waves",
    "edge": "the outside limit of an object, area, or surface",
    "edit": "prepare (written material) for publication by correcting, condensing, or modifying it",
    "eggs": "plural of egg; an oval or round object laid by a female bird, reptile, fish, or invertebrate",
    "else": "in addition; besides",
    "emit": "produce and discharge (something, especially gas, radiation, or smell)",
    "ends": "plural of end; a final part of something",
    "epic": "relating to or characteristic of an epic or epics",
    "even": "flat and smooth",
    "ever": "at any time",
    "evil": "profoundly immoral and malevolent",
    "exam": "a formal test of a person's knowledge or proficiency in a particular subject",
    "exit": "a way out, especially of a public building, room, or passenger vehicle",
    "eyes": "plural of eye; each of a pair of globular organs in the head",
    "face": "the front part of a person's head from the forehead to the chin",
    "fact": "a thing that is indisputably the case",
    "fade": "gradually grow faint and disappear",
    "fail": "be unsuccessful in achieving one's goal",
    "fair": "treating people equally without favoritism or discrimination",
    "fall": "move downward, typically rapidly and freely without control",
    "fame": "the condition of being known or talked about by many people",
    "farm": "an area of land and its buildings used for growing crops and rearing animals",
    "fast": "moving or capable of moving at high speed",
    "fate": "the development of events beyond a person's control",
    "fear": "an unpleasant emotion caused by the belief that someone or something is dangerous",
    "feel": "experience (an emotion or sensation)",
    "feet": "plural of foot; the terminal part of the leg below the ankle",
    "fell": "past tense of fall",
    "felt": "past and past participle of feel",
    "fern": "a flowerless plant which has feathery or leafy fronds",
    "file": "a folder or box for holding loose papers that are typically arranged in a particular order",
    "fill": "cause (a space or container) to become full or almost full",
    "film": "a story or event recorded by a camera as a set of moving images",
    "find": "discover or perceive by chance or unexpectedly",
    "fine": "of high quality; very good of its kind",
    "fire": "combustion or burning, in which substances combine chemically with oxygen",
    "firm": "having a solid, almost unyielding surface or structure",
    "fish": "a limbless cold-blooded vertebrate animal with gills and fins",
    "fist": "a person's hand when the fingers are bent in toward the palm",
    "five": "equivalent to the sum of two and three; one more than four",
    "flag": "a piece of cloth with a distinctive design and colors",
    "flat": "having a level surface; not curved or sloped",
    "flew": "past tense of fly",
    "flip": "turn over or cause to turn over with a sudden sharp movement",
    "flow": "move along or out steadily and continuously in a current or stream",
    "foam": "a mass of small bubbles formed on or in liquid",
    "fold": "bend (something flexible and relatively flat) over on itself",
    "folk": "people in general",
    "food": "any nutritious substance that people or animals eat or drink",
    "fool": "a person who acts unwisely or imprudently; a silly person",
    "foot": "the terminal part of the leg below the ankle",
    "fork": "an implement with two or more prongs used for lifting food to the mouth",
    "form": "the visible shape or configuration of something",
    "fort": "a military stronghold, especially a strongly fortified town",
    "four": "equivalent to the product of two and two; one more than three",
    "free": "not under the control or in the power of another",
    "from": "indicating the point in space at which a journey, motion, or action starts",
    "fuel": "material such as coal, gas, or oil that is burned to produce heat or power",
    "full": "containing or holding as much or as many as possible",
    "fund": "a sum of money saved or made available for a particular purpose",
    "fuse": "join or blend to form a single entity",
    "gain": "obtain or secure (something desired, favorable, or profitable)",
    "game": "a form of play or sport, especially a competitive one played according to rules",
    "gang": "an organized group of criminals",
    "gate": "a hinged barrier used to close an opening in a wall, fence, or hedge",
    "gave": "past tense of give",
    "gear": "equipment that is used for a particular purpose",
    "gene": "a unit of heredity which is transferred from a parent to offspring",
    "gift": "a thing given willingly to someone without payment",
    "girl": "a female child",
    "give": "freely transfer the possession of (something) to (someone)",
    "glad": "feeling pleasure or happiness",
    "glow": "give out steady light without flame",
    "goal": "the object of a person's ambition or effort; an aim or desired result",
    "goat": "a hardy domesticated ruminant animal that has backward curving horns",
    "gods": "plural of god; a superhuman being or spirit worshiped as having power",
    "goes": "third person singular present of go",
    "gold": "a precious metal, the chemical element of atomic number 79",
    "golf": "a club-and-ball sport in which players use various clubs to hit balls into holes",
    "gone": "past participle of go",
    "good": "to be desired or approved of",
    "grab": "grasp or seize suddenly and roughly",
    "gray": "of a color intermediate between black and white",
    "grew": "past tense of grow",
    "grid": "a framework of spaced bars that are parallel to or cross each other",
    "grim": "forbidding or harsh in appearance",
    "grip": "take and keep a firm hold of; grasp tightly",
    "grow": "increase in size, number, strength, or quality",
    "gulf": "a large bay that is an arm of an ocean or sea",
    "hair": "any of the fine threadlike strands growing from the skin of humans, mammals",
    "half": "either of two equal or corresponding parts into which something is or can be divided",
    "hall": "the room or space just inside the front entrance of a house",
    "hand": "the terminal part of the human arm located below the forearm",
    "hang": "suspend or be suspended from above with the lower part dangling free",
    "hard": "solid, firm, and resistant to pressure; not easily broken, bent, or pierced",
    "harm": "physical injury, especially that which is deliberately inflicted",
    "hate": "feel intense or passionate dislike for (someone)",
    "have": "possess, own, or hold",
    "head": "the upper part of the human body, or the front or upper part of an animal's body",
    "heal": "cause (a wound, injury, or person) to become sound or healthy again",
    "hear": "perceive with the ear the sound made by (someone or something)",
    "heat": "the quality of being hot; high temperature",
    "held": "past and past participle of hold",
    "hell": "a place regarded in various religions as a spiritual realm of evil and suffering",
    "help": "make it easier for (someone) to do something by offering aid",
    "herb": "any plant with leaves, seeds, or flowers used for flavoring, food, medicine",
    "herd": "a large group of animals, especially hoofed mammals, that live together",
    "here": "in, at, or to this place or position",
    "hero": "a person who is admired or idealized for courage, outstanding achievements",
    "hide": "put or keep out of sight; conceal from the view or knowledge of others",
    "high": "of great vertical extent",
    "hill": "a naturally raised area of land, not as high or craggy as a mountain",
    "hint": "a slight or indirect indication or suggestion",
    "hire": "employ (someone) for wages",
    "hits": "strikes (someone or something) quickly and forcefully with the hand or an implement",
    "hold": "grasp, carry, or support with one's arms or hands",
    "hole": "a hollow place in a solid body or surface",
    "holy": "dedicated or consecrated to God or a religious purpose; sacred",
    "home": "the place where one lives permanently",
    "hood": "a covering for the head and neck with an opening for the face",
    "hook": "a piece of metal or other material, curved or bent back at an angle",
    "hope": "a feeling of expectation and desire for a certain thing to happen",
    "horn": "a hard, permanent outgrowth, often curved and pointed",
    "host": "a person who receives or entertains other people as guests",
    "hour": "a period of time equal to a twenty-fourth part of a day and night",
    "huge": "extremely large; enormous",
    "hunt": "pursue and kill (a wild animal) for sport or food",
    "hurt": "cause pain or injury to",
    "icon": "a painting of Jesus Christ or another holy figure, typically in a traditional style",
    "idea": "a thought or suggestion as to a possible course of action",
    "idle": "not active or in use",
    "inch": "a unit of linear measure equal to one twelfth of a foot",
    "info": "information (informal)",
    "iron": "a strong, hard magnetic silvery-gray metal",
    "item": "an individual article or unit, especially one that is part of a list",
    "jack": "a device for lifting heavy objects, especially one for raising the axle of a motor vehicle",
    "jade": "a hard, typically green stone used for ornaments and implements",
    "jail": "a place for the confinement of people accused or convicted of a crime",
    "jazz": "a type of music of black American origin characterized by improvisation",
    "join": "link; connect",
    "joke": "a thing that someone says to cause amusement or laughter",
    "jump": "push oneself off a surface and into the air by using the muscles in one's legs and feet",
    "june": "the sixth month of the year",
    "jury": "a body of people sworn to give a verdict in a legal case",
    "just": "based on or behaving according to what is morally right and fair",
    "keep": "have or retain possession of",
    "kept": "past and past participle of keep",
    "keys": "plural of key; a small piece of shaped metal with incisions cut to fit the wards of a particular lock",
    "kick": "strike or propel forcibly with the foot",
    "kids": "plural of kid; a child or young person (informal)",
    "kill": "cause the death of (a person, animal, or other living thing)",
    "kind": "having or showing a friendly, generous, or considerate nature",
    "king": "the male ruler of an independent state",
    "kiss": "touch with the lips as a sign of love, sexual desire, reverence, or greeting",
    "kite": "a toy consisting of a light frame with thin material stretched over it",
    "knee": "the joint between the thigh and the lower leg in humans",
    "knew": "past tense of know",
    "knot": "a fastening made by tying a piece of string, rope, or something similar",
    "know": "be aware of through observation, inquiry, or information",
    "lack": "the state of being without or not having enough of something",
    "lady": "a woman of superior social position",
    "laid": "past and past participle of lay",
    "lake": "a large area of water surrounded by land",
    "lamb": "a young sheep",
    "lamp": "a device for giving light, either one consisting of an electric bulb",
    "land": "the part of the earth's surface that is not covered by water",
    "lane": "a narrow road, especially in a rural area",
    "last": "coming after all others in time or order; final",
    "late": "doing something or taking place after the expected, proper, or usual time",
    "lawn": "an area of short, mown grass in a yard, garden, or park",
    "lazy": "unwilling to work or use energy",
    "lead": "cause (a person or animal) to go with one by holding them by the hand",
    "leaf": "a flattened structure of a higher plant, typically green and blade-like",
    "lean": "be in or move into a sloping position",
    "left": "on, toward, or relating to the side of a human body or of a thing",
    "legs": "plural of leg; each of the limbs on which a person or animal walks and stands",
    "lens": "a piece of glass or other transparent substance with curved sides",
    "less": "a smaller amount of; not as much",
    "life": "the condition that distinguishes animals and plants from inorganic matter",
    "lift": "raise to a higher position or level",
    "lime": "a rounded citrus fruit similar to a lemon but greener, smaller, and more acidic",
    "line": "a long narrow mark or band",
    "link": "a relationship between two things or situations",
    "lion": "a large tawny-colored cat that lives in prides",
    "lips": "plural of lip; either of the two fleshy parts that form the edges of the mouth",
    "list": "a number of connected items or names written or printed consecutively",
    "live": "remain alive",
    "load": "a heavy or bulky thing that is being carried or is about to be carried",
    "loan": "a thing that is borrowed, especially a sum of money",
    "lock": "a mechanism for keeping a door, lid, etc., fastened",
    "long": "measuring a great distance from end to end",
    "look": "direct one's gaze toward someone or something or in a specified direction",
    "loop": "a shape produced by a curve that bends around and crosses itself",
    "lord": "a man of noble rank or high office",
    "lose": "be deprived of or cease to have or retain (something)",
    "loss": "the fact or process of losing something or someone",
    "lost": "past and past participle of lose",
    "lots": "a great deal; a large number or amount",
    "loud": "producing or capable of producing much noise",
    "love": "an intense feeling of deep affection",
    "luck": "success or failure apparently brought by chance rather than through one's own actions",
    "lump": "a compact mass of a substance, especially one without a definite or regular shape",
    "lung": "each of the pair of organs situated within the ribcage",
    "made": "past and past participle of make",
    "mail": "letters and packages conveyed by a postal system",
    "main": "chief in size or importance; principal",
    "make": "form (something) by putting parts together or combining substances",
    "male": "of or denoting the sex that produces small, typically motile gametes",
    "mall": "a large enclosed shopping area from which traffic is excluded",
    "many": "a large number of",
    "maps": "plural of map; a diagrammatic representation of an area of land or sea",
    "mark": "a small area on a surface having a different color from its surroundings",
    "mars": "the fourth planet from the sun in the solar system",
    "mask": "a covering for all or part of the face, worn as a disguise",
    "mass": "a coherent, typically large body of matter with no definite shape",
    "mate": "the sexual partner of a bird or other animal",
    "math": "the abstract science of number, quantity, and space",
    "meal": "any of the regular occasions in a day when a reasonably large amount of food is eaten",
    "mean": "intend to convey, indicate, or refer to (a particular thing or notion)",
    "meat": "the flesh of an animal (especially a mammal) as food",
    "meet": "encounter (someone) unexpectedly or by chance",
    "melt": "make or become liquid, typically as a result of heat",
    "memo": "a written message, especially in business; a memorandum",
    "menu": "a list of dishes available in a restaurant",
    "mesh": "material made of a network of wire or thread",
    "mice": "plural of mouse; a small rodent that typically has a pointed snout",
    "mild": "not severe, serious, or harsh",
    "milk": "an opaque white fluid rich in fat and protein",
    "mind": "the element of a person that enables them to be aware of the world",
    "mine": "used to refer to a thing or things belonging to or associated with the speaker",
    "mint": "an aromatic plant native to temperate regions of the Old World",
    "miss": "fail to hit, reach, or come into contact with (something aimed at)",
    "mist": "a cloud of tiny water droplets suspended in the atmosphere at ground level",
    "mode": "a way or manner in which something occurs or is experienced",
    "mood": "a temporary state of mind or feeling",
    "moon": "the natural satellite of the earth, visible (chiefly at night) by reflected light",
    "more": "a greater or additional amount or degree",
    "most": "greatest in amount, quantity, or degree",
    "move": "go in a specified direction or manner; change position",
    "much": "a large amount of",
    "mule": "the offspring of a donkey and a horse",
    "myth": "a traditional story, especially one concerning the early history of a people",
    "name": "a word or set of words by which a person, animal, place, or thing is known",
    "navy": "the branch of the armed services of a state which conducts military operations at sea",
    "near": "at or to a short distance away; nearby",
    "neck": "the part of a person's or animal's body connecting the head to the rest of the body",
    "need": "require (something) because it is essential or very important",
    "nest": "a structure or place made or chosen by a bird for laying eggs and sheltering its young",
    "news": "newly received or noteworthy information, especially about recent or important events",
    "next": "coming immediately after the time of writing or speaking",
    "nice": "pleasant; agreeable; satisfactory",
    "nine": "equivalent to the product of three and three; one more than eight",
    "node": "a point in a network or diagram at which lines or systems intersect",
    "none": "not any; no amount of something",
    "noon": "twelve o'clock in the day; midday",
    "norm": "a standard or pattern that is typical or expected",
    "nose": "the part of the face that contains the nostrils and organs of smell",
    "note": "a brief written record for future reference",
    "noun": "a word that names a person, place, thing, or idea",
    "oath": "a solemn promise, often invoking a divine witness",
    "obey": "to comply with the command or request of someone",
    "oboe": "a woodwind instrument with a double reed",
    "odds": "the ratio between amounts staked; probability",
    "ogle": "to stare at in a lecherous manner",
    "oily": "covered with or containing oil; greasy",
    "okay": "satisfactory; all right; acceptable",
    "once": "on one occasion or for one time only",
    "only": "and no one or nothing more besides; solely",
    "onto": "moving to a location on the surface of something",
    "onus": "something that is one's duty or responsibility",
    "onyx": "a semi-precious stone consisting of banded chalcedony",
    "oops": "used to show recognition of a mistake or minor accident",
    "open": "allowing access or passage; not closed or blocked",
    "opus": "a separate composition or set of compositions",
    "oral": "spoken rather than written; relating to the mouth",
    "orca": "a large black and white predatory marine mammal",
    "ouch": "used to express pain or annoyance",
    "ours": "belonging to or associated with us",
    "oust": "to drive out or expel someone from a position",
    "oval": "having a rounded and slightly elongated shape like an egg",
    "oven": "an enclosed compartment for cooking and heating food",
    "over": "extending directly upward from; above",
    "pace": "a single step taken when walking or running; speed",
    "pack": "a collection of items wrapped together for carrying",
    "pact": "a formal agreement between individuals or parties",
    "page": "one side of a sheet of paper in a book, magazine, etc.",
    "paid": "past tense of pay; having given money for goods",
    "pain": "physical suffering caused by illness or injury",
    "pair": "a set of two things used together or regarded as a unit",
    "pale": "light in color or having less color than normal",
    "palm": "the inner surface of the hand between the wrist and fingers",
    "pane": "a single sheet of glass in a window or door",
    "park": "a large public green area used for recreation",
    "part": "a piece or segment of something such as an object",
    "pass": "to move or proceed onward; to transfer",
    "past": "gone by in time and no longer existing",
    "path": "a way or track laid down for walking",
    "peak": "the pointed top of a mountain; the highest point",
    "pear": "a sweet, juicy fruit with a narrow top and wide bottom",
    "peat": "a brown, soil-like material consisting of partly decomposed matter",
    "peek": "to look quickly or furtively",
    "peel": "the outer covering of a fruit or vegetable",
    "peer": "to look with difficulty or concentration",
    "pelt": "to attack by repeatedly throwing things",
    "pend": "to await judgment or settlement",
    "pens": "writing instruments that use ink",
    "pent": "closely confined; shut in",
    "perk": "a benefit or advantage provided to an employee",
    "perm": "a hairstyle produced by setting the hair in waves and treating it with chemicals",
    "pest": "a destructive insect or animal that attacks crops or livestock",
    "pews": "long benches with backs, used for seating in a church",
    "pica": "a unit of type size and measure in printing",
    "pick": "to select from a number of alternatives",
    "pier": "a structure leading out to sea, used as a landing place",
    "pies": "baked dishes of fruit, meat, or vegetables, typically with a top and base of pastry",
    "pigs": "omnivorous domesticated hoofed mammals with sparse bristly hair",
    "pike": "a predatory freshwater fish with a long body and sharp teeth",
    "pile": "a heap of things laid or lying one on top of another",
    "pill": "a small round mass of solid medicine for swallowing whole",
    "pimp": "a man who controls prostitutes and arranges clients for them",
    "pine": "an evergreen coniferous tree with clusters of long needle-shaped leaves",
    "pink": "a color combining red and white; of a pale red color",
    "pins": "small thin pieces of metal with a sharp point used for fastening",
    "pint": "a unit of liquid or dry capacity equal to half a quart",
    "pipe": "a tube of metal, plastic, or other material used to convey water, gas, etc.",
    "pita": "a type of flat, hollow, slightly leavened bread",
    "pits": "large holes in the ground; the stone of a fruit",
    "plan": "a detailed proposal for doing or achieving something",
    "play": "to engage in activity for enjoyment and recreation",
    "plea": "a request made in an urgent and emotional manner",
    "plod": "to walk doggedly and slowly with heavy steps",
    "plot": "a plan made in secret by a group of people to do something illegal",
    "plow": "a large farming implement with one or more blades used to cut soil",
    "plug": "a piece of solid material fitting tightly into a hole and blocking it",
    "plum": "an oval fleshy fruit that is purple, reddish, or yellow when ripe",
    "plus": "with the addition of; and also",
    "poem": "a piece of writing that partakes of the nature of both speech and song",
    "poet": "a person who writes poems",
    "poke": "to jab or prod with a finger or a sharp object",
    "pole": "a long, slender piece of wood or metal, often used as a support",
    "poll": "the process of voting in an election or a survey of public opinion",
    "polo": "a game of Eastern origin played on horseback with mallets and a wooden ball",
    "pond": "a small body of still water formed naturally or by artificial means",
    "pony": "a horse of a small breed, especially one below 15 hands",
    "pool": "a small area of still water, typically one formed naturally",
    "poor": "lacking sufficient money to live at a standard considered comfortable",
    "pore": "to be absorbed in reading or studying something",
    "pork": "the flesh of a pig used as food",
    "port": "a town or city with a harbor where ships load or unload",
    "pose": "to present or constitute (a problem, danger, or question)",
    "post": "a long, sturdy piece of timber or metal set upright in the ground",
    "pour": "to flow or cause to flow in a steady stream",
    "pout": "to push one's lips or bottom lip forward as an expression of petulance",
    "pram": "a four-wheeled carriage for a baby, pushed by a person on foot",
    "pray": "to address a solemn request to a deity or other object of worship",
    "prey": "an animal that is hunted and killed by another for food",
    "prep": "to prepare something; preparation",
    "prim": "stiffly formal and respectable; feeling or showing disapproval of anything improper",
    "prod": "to poke with a finger, foot, or pointed object",
    "prom": "a formal dance, especially one held by a high school at the end of the academic year",
    "prop": "a pole or beam used as a support or to keep something in position",
    "pros": "arguments or considerations in favor of something; advantages",
    "puff": "a short, explosive burst of breath or wind",
    "pull": "to exert force on someone or something so as to cause movement toward oneself",
    "pulp": "a soft, wet, shapeless mass of material",
    "puma": "a large American wild cat with a plain tawny to grayish coat",
    "pump": "a mechanical device using suction or pressure to raise or move liquids or gases",
    "punk": "a loud, fast-moving, and aggressive form of rock music",
    "punt": "to kick a ball after it is dropped from the hands and before it touches the ground",
    "puny": "small and weak",
    "pupa": "an insect in its inactive immature form between larva and adult",
    "pure": "not mixed or adulterated with any other substance or material",
    "purr": "a low continuous vibratory sound made by a cat",
    "push": "to exert force on someone or something so as to move them away from oneself",
    "puss": "a cat, or a child's word for a cat",
    "putt": "to try to hit a golf ball into the hole with a light stroke",
    "quad": "a square or rectangular area or courtyard, especially on a college campus",
    "quay": "a stone or metal platform lying alongside or projecting into water for loading and unloading ships",
    "quid": "one pound sterling in British money",
    "quip": "a witty remark or comment",
    "quit": "to leave or stop doing something permanently",
    "quiz": "a test of knowledge, especially as a competition between individuals or teams",
    "race": "a competition of speed between runners, vehicles, horses, etc.",
    "rack": "a framework, typically with rails, bars, hooks, or pegs, for holding or storing things",
    "rage": "violent, uncontrollable anger",
    "raid": "a sudden surprise attack on an enemy or a search of premises by police",
    "rail": "a bar or series of bars, typically fixed on upright supports, serving as a fence or barrier",
    "rain": "moisture condensed from the atmosphere that falls visibly in separate drops",
    "rake": "a tool with a long handle and prongs at the end, used for gathering leaves or loose material",
    "ramp": "a sloping surface joining two different levels",
    "rang": "past tense of ring; made a clear resonant or vibrating sound",
    "rank": "a position in a hierarchy, especially in the military or police",
    "rant": "to speak or shout at length in a wild, impassioned way",
    "rare": "not occurring very often; uncommon",
    "rash": "an area of red spots on the skin caused by illness or reaction to something",
    "rate": "a measure, quantity, or frequency, typically one measured against another quantity",
    "rave": "to talk wildly or incoherently; speak enthusiastically about something",
    "read": "to look at and comprehend the meaning of written or printed matter",
    "real": "actually existing as a thing or occurring in fact; not imagined or supposed",
    "ream": "a large quantity of something, especially paper",
    "rear": "the back part of something; to bring up and care for offspring",
    "reef": "a ridge of jagged rock, coral, or sand just above or below the surface of the sea",
    "reel": "a cylinder on which film, wire, thread, etc., can be wound; to stagger or sway",
    "rely": "to depend on with full trust or confidence",
    "rent": "a tenant's regular payment to a landlord for the use of property or land",
    "rest": "to cease work or movement in order to relax, refresh oneself, or recover strength",
    "ribs": "the curved bones that form the rib cage protecting the chest",
    "rice": "small edible white or brown grains from a cereal plant",
    "rich": "having abundant wealth or valuable resources",
    "ride": "to sit on and control the movement of an animal or vehicle",
    "rift": "a crack, split, or break in something",
    "ring": "a small circular band worn as jewelry; to make a resonant sound",
    "ripe": "fully matured or developed and ready to be eaten or used",
    "rise": "to move from a lower position to a higher one",
    "risk": "a situation involving exposure to danger",
    "road": "a wide way leading from one place to another",
    "roam": "to move about or travel aimlessly or unsystematically",
    "roar": "a full, deep, prolonged loud sound",
    "robe": "a long loose outer garment",
    "rock": "a solid mineral material; to move gently back and forth",
    "role": "the function assumed or part played by a person or thing",
    "roll": "to move by turning over and over on an axis",
    "roof": "the structure forming the upper covering of a building",
    "room": "a part or division of a building enclosed by walls",
    "root": "the part of a plant that attaches to the ground for support and nutrients",
    "rope": "a strong thick cord made by twisting fibers together",
    "sage": "a profoundly wise person; also an herb used in cooking",
    "sail": "to travel in a boat using wind for movement",
    "salt": "a white crystalline substance used for seasoning",
    "sand": "fine granular material found on beaches and deserts",
    "save": "to keep safe or rescue from harm; to store",
    "scan": "to look over quickly; to digitally read",
    "scar": "a mark left on the skin after a wound heals",
    "seal": "a sea animal; also to close tightly",
    "seat": "a thing made for sitting",
    "seed": "the small part of a plant that can grow into a new plant",
    "seek": "to attempt to find or obtain",
    "seem": "to give the impression of being",
    "seen": "past participle of see; observed",
    "self": "a person's essential being",
    "sell": "to exchange something for money",
    "send": "to cause to go or be taken to a destination",
    "sent": "past tense of send",
    "ship": "a large vessel for traveling on water",
    "shop": "a place where goods are sold",
    "shot": "a fired projectile; a medical injection; an attempt",
    "show": "to display or allow to be seen",
    "shut": "to close something",
    "sick": "affected by illness",
    "side": "a position to the left or right of something",
    "sift": "to pass something through a sieve",
    "sign": "a mark or symbol conveying information",
    "silk": "a fine, strong soft fiber made by silkworms",
    "sing": "to make musical sounds with the voice",
    "sink": "to go down below the surface",
    "site": "a location or place",
    "size": "the overall dimensions or magnitude of something",
    "skin": "the outer covering of a body",
    "skip": "to jump lightly from one foot to another; to omit",
    "slam": "to close violently with a bang",
    "slip": "to slide unintentionally; a small mistake",
    "slow": "not fast; taking a long time",
    "snow": "frozen white precipitation",
    "soap": "a substance used for washing",
    "soar": "to fly or rise high in the air",
    "soil": "earth or ground; to make dirty",
    "sold": "past tense of sell",
    "sole": "the only one; also the bottom of a foot or shoe",
    "some": "an unspecified amount or number",
    "song": "a musical composition with vocals",
    "soon": "in a short time",
    "soul": "the spiritual or immaterial part of a person",
    "sour": "having an acidic taste",
    "span": "the full reach or extent between two points",
    "spin": "to rotate rapidly",
    "spot": "a small round mark; to notice",
    "star": "a celestial body producing light; a famous person",
    "stay": "to remain in place",
    "stem": "the main stalk of a plant",
    "step": "a movement of the foot; a stage of progress",
    "stop": "to cease movement or action",
    "store": "to keep for future use",
    "storm": "a violent weather condition",
    "swap": "to exchange one thing for another",
    "swim": "to move through water using limbs",
    "tail": "the back end of an animal",
    "take": "to grasp, acquire, or get hold of",
    "tale": "a story, especially imaginative or fictitious",
    "talk": "to speak in order to communicate",
    "tall": "of greater than average height",
    "tank": "a large container for liquid; a military vehicle",
    "tape": "a narrow strip of material for binding or recording",
    "task": "a piece of work to be done",
    "tear": "to rip something apart; or a drop from the eye",
    "team": "a group working together",
    "tell": "to communicate information",
    "tend": "to take care of; to be inclined toward",
    "tent": "a portable shelter made of fabric",
    "term": "a fixed period of time; a word or expression",
    "test": "an examination of knowledge or ability",
    "text": "written or printed words",
    "than": "used in comparisons",
    "that": "used to identify a specific thing",
    "them": "refers to people or things previously mentioned",
    "then": "at that time; next",
    "thin": "having little thickness",
    "this": "used to identify something close by",
    "thou": "an archaic form of 'you'",
    "thus": "as a result; in this way",
    "tide": "the rise and fall of sea levels",
    "till": "up to the time of",
    "time": "the ongoing progression of events",
    "tire": "to become weary; a rubber covering for a wheel",
    "toil": "to work extremely hard",
    "told": "past tense of tell",
    "toll": "a charge or fee; a ringing of a bell",
    "tone": "a musical or vocal sound",
    "tool": "a device used to carry out a task",
    "tour": "a journey for pleasure",
    "town": "a populated urban area smaller than a city",
    "trap": "a device for catching things; to catch",
    "tree": "a tall plant with a trunk and branches",
    "trim": "to cut away excess; neat and tidy",
    "true": "in accordance with fact or reality",
    "tube": "a hollow cylindrical object",
    "tune": "a melody or musical composition",
    "turn": "to move in a circular direction",
    "type": "a category or kind",
    "ugly": "unpleasant to look at",
    "unit": "a single thing regarded as part of a whole",
    "urge": "to strongly recommend or persuade",
    "used": "employed for a purpose; not new",
    "user": "a person who uses something",
    "vain": "having excessive pride; futile",
    "vast": "very large in size or extent",
    "veil": "a piece of cloth worn to cover the face or head",
    "vent": "an opening that allows air or gas to pass",
    "verb": "a word that expresses an action or state",
    "very": "to a high degree; extremely",
    "veto": "to reject or forbid formally",
    "view": "a sight or panorama; an opinion",
    "vine": "a climbing or trailing plant",
    "vote": "a formal expression of choice",
    "wade": "to walk through shallow water",
    "wage": "payment for work",
    "wait": "to stay where one is until something happens",
    "wake": "to stop sleeping",
    "walk": "to move on foot at a moderate pace",
    "wall": "a vertical structure dividing or enclosing an area",
    "want": "to desire something",
    "ward": "a division of a hospital or city",
    "warm": "moderately hot",
    "warn": "to inform of possible danger",
    "wash": "to clean with water",
    "wave": "a moving ridge of water; a gesture of greeting",
    "weak": "lacking strength",
    "wear": "to have clothing on the body",
    "weed": "an undesirable plant",
    "week": "a period of seven days",
    "weep": "to shed tears",
    "well": "in a good or satisfactory way; also a water source",
    "west": "the direction where the sun sets",
    "what": "asking for information about something",
    "when": "asking about time",
    "whip": "to beat or strike; a tool for striking",
    "wide": "broad; having great width",
    "wild": "living or growing in a natural, untamed state",
    "wind": "moving air; also to twist or turn",
    "wine": "an alcoholic drink made from fermented grapes",
    "wing": "one of the limbs birds use for flying",
    "wipe": "to clean or dry by rubbing",
    "wire": "thin flexible metal strand",
    "wise": "having experience or good judgment",
    "wish": "to want something to happen",
    "with": "accompanied by",
    "wood": "the hard material from trees",
    "wool": "the soft hair from sheep",
    "word": "a unit of language",
    "work": "physical or mental effort",
    "worm": "a small invertebrate creature",
    "worn": "damaged or thin from use; past participle of wear",
    "wrap": "to cover or enclose something",
    "yard": "a unit of length equal to 3 feet; an outdoor area",
    "yarn": "spun thread for knitting or weaving",
    "yawn": "to open the mouth wide from tiredness or boredom",
    "year": "a period of twelve months",
    "yell": "to shout loudly",
    "yolk": "the yellow inner part of an egg",
    "zero": "the number representing no quantity",
    "zinc": "a metallic chemical element",
    "zone": "an area with particular characteristics",
}

fours_list = fours_json.keys()
