sixes_json = {
    "abacus": "A frame with wires or rods on which beads are slid, used for calculating",
    "abduct": "To take someone away illegally by force or deception",
    "abound": "To exist in large numbers or amounts",
    "abroad": "In or to a foreign country or countries",
    "abrupt": "Sudden and unexpected",
    "absent": "Not present in a place, at an occasion, or as part of something",
    "absorb": "To take in or soak up (a liquid or other substance)",
    "absurd": "Wildly unreasonable, illogical, or inappropriate",
    "accent": "A distinctive mode of pronunciation of a language",
    "accept": "To consent to receive or undertake something offered",
    "access": "A means of approaching or entering a place",
    "accord": "An official agreement or treaty",
    "accuse": "To charge someone with an offense or crime",
    "across": "From one side to the other of a place, area, etc.",
    "action": "The fact or process of doing something, typically to achieve an aim",
    "active": "Engaging or ready to engage in physically energetic pursuits",
    "actual": "Existing in fact; real",
    "adapts": "Makes something suitable for a new use or purpose",
    "addict": "A person who is addicted to a particular substance or activity",
    "adhere": "To stick fast to a surface or substance",
    "adjust": "To alter or move something slightly in order to achieve the desired fit, appearance, or result",
    "admire": "To regard with respect or warm approval",
    "admit": "To confess to be true or to be the case",
    "adobe": "A kind of clay used as a building material",
    "adopt": "To legally take another's child and bring it up as one's own",
    "adore": "To love and respect someone deeply",
    "adorn": "To make more beautiful or attractive",
    "adults": "A person who is fully grown or developed",
    "advice": "Guidance or recommendations offered with regard to prudent future action",
    "advise": "To offer suggestions about the best course of action to someone",
    "aerial": "Existing, happening, or operating in the air",
    "affair": "An event or sequence of events of a specified kind or that has previously been referred to",
    "affect": "To have an effect on; make a difference to",
    "afford": "To have enough money to pay for",
    "afraid": "Feeling fear or anxiety; frightened",
    "ageing": "The process of growing old",
    "agency": "A business or organization established to provide a particular service",
    "agenda": "A list of items to be discussed at a formal meeting",
    "agents": "A person who acts on behalf of another",
    "agreed": "Discussed and accepted by all parties",
    "ahead": "Further forward in space or time",
    "aiding": "Providing help, support, or relief",
    "ailing": "In poor health",
    "aiming": "Point or direct a weapon or camera at a target",
    "alarms": "A warning of danger, usually signaled by a sound or light",
    "albums": "A blank book for the insertion of photographs, stamps, or pictures",
    "alerts": "Quick to notice any unusual and potentially dangerous or difficult circumstances",
    "aliens": "A being from another world",
    "aligns": "Places or arranges things in a straight line",
    "alleys": "A narrow passageway between or behind buildings",
    "allied": "Joined by or relating to members of an alliance",
    "allows": "To give permission for someone to do something or for something to happen",
    "almost": "Not quite; very nearly",
    "alphas": "The first letter of the Greek alphabet",
    "alpine": "Relating to high mountains",
    "altars": "A table or flat-topped block used as the focus for a religious ritual",
    "alters": "To change or cause to change in character or composition",
    "amazed": "Greatly surprised; astounded",
    "amazon": "A member of a legendary race of female warriors",
    "ambers": "A hard, translucent, yellowish-brown fossil resin",
    "ambush": "A surprise attack by people lying in wait in a concealed position",
    "amends": "To make minor changes to a text, law, or document to make it fairer or more accurate",
    "amidst": "In the middle of",
    "amount": "A quantity of something, especially the total of a thing or things in number, size, value, or extent",
    "amused": "Finding something entertaining or funny",
    "analog": "Relating to or using signals or information represented by a continuously variable physical quantity",
    "anchor": "A heavy object used to moor a ship to the sea bottom",
    "anemia": "A condition marked by a deficiency of red blood cells or of hemoglobin in the blood",
    "angelic": "Relating to or resembling angels, especially in being beautiful, pure, or kind",
    "angels": "A spiritual being believed to act as an attendant, agent, or messenger of God",
    "angled": "A space between two lines or surfaces that meet at a point",
    "animal": "A living organism that feeds on organic matter, typically having specialized sense organs and nervous system",
    "ankles": "The joint connecting the foot with the leg",
    "annals": "A record of events year by year",
    "annexe": "A building joined to or associated with a main building",
    "annoys": "To irritate someone; make someone a little angry",
    "annual": "Occurring once every year",
    "answer": "A thing said, written, or done to deal with or as a reaction to a question, statement, or situation",
    "antics": "Foolish, outrageous, or amusing behavior",
    "antler": "One of the two branched horns on the head of an adult deer",
    "anyhow": "Anyway; regardless",
    "anyone": "Any person or people",
    "anyway": "Used to confirm or support a point or idea just mentioned",
    "apathy": "Lack of interest, enthusiasm, or concern",
    "apiece": "To, for, or by each one of a group",
    "apollo": "The ancient Greek and Roman god of sun, light, music, and poetry",
    "aprons": "A protective garment worn over the front of one's clothes and tied at the back",
    "arcade": "A covered passageway with arches along one or both sides",
    "archer": "A person who shoots with a bow and arrows",
    "arctic": "The regions around the North Pole",
    "ardent": "Very enthusiastic or passionate",
    "arenas": "A level area surrounded by seats for spectators, in which sports, entertainments, and other public events are held",
    "argued": "To give reasons or cite evidence in support of an idea, action, or theory",
    "arises": "To come into existence; to occur",
    "armada": "A fleet of warships",
    "armies": "An organized military force equipped for fighting on land",
    "armors": "The metal coverings formerly worn to protect the body in battle",
    "aromas": "A distinctive, typically pleasant smell",
    "around": "Located or situated on every side",
    "arouse": "To evoke or awaken a feeling, emotion, or response",
    "arrays": "An impressive display or range of a particular type of thing",
    "arrest": "To seize someone by legal authority and take into custody",
    "arrive": "To reach a place at the end of a journey or a stage in a journey",
    "arrows": "A weapon consisting of a thin, straight stick with a sharp point, designed to be shot from a bow",
    "artery": "Any of the muscular-walled tubes forming part of the circulation system by which blood is conveyed from the heart to all parts of the body",
    "artful": "Clever or skillful, typically in a crafty or cunning way",
    "artist": "A person who creates paintings or drawings as a profession or hobby",
    "ascend": "To go up or climb",
    "ascent": "A climb or walk to the summit of a mountain or hill",
    "ashore": "To or on the shore from the direction of the sea",
    "asleep": "In a state of sleep",
    "aspect": "A particular part or feature of something",
    "assent": "The expression of approval or agreement",
    "assert": "To state a fact or belief confidently and forcefully",
    "assess": "To evaluate or estimate the nature, ability, or quality of",
    "assets": "A useful or valuable thing, person, or quality",
    "assign": "To allocate a job or duty",
    "assist": "To help someone",
    "assume": "To suppose to be the case, without proof",
    "assure": "To tell someone something positively or confidently to dispel any doubts",
    "asthma": "A respiratory condition marked by spasms in the bronchi of the lungs, causing difficulty in breathing",
    "astral": "Relating to or resembling the stars",
    "astray": "Away from the correct path or direction",
    "astute": "Having or showing an ability to accurately assess situations or people and turn this to one's advantage",
    "atomic": "Relating to an atom or atoms",
    "atonal": "Music that is not written in any key or mode",
    "atrium": "A central hall or court in a modern building, typically rising through several stories and having a glazed roof",
    "attach": "To join or fasten something to something else",
    "attack": "To take aggressive action against with weapons or armed force",
    "attain": "To succeed in achieving something that one has worked for",
    "attend": "To be present at an event, meeting, or function",
    "attest": "To provide or serve as clear evidence of",
    "attics": "A space or room just below the roof of a building",
    "attire": "Clothes, especially fine or formal ones",
    "attune": "To make receptive or aware",
    "auburn": "A reddish-brown color",
    "audios": "Sound, especially when recorded, transmitted, or reproduced",
    "audits": "An official inspection of an organization's accounts",
    "august": "Respected and impressive",
    "author": "A writer of a book, article, or report",
    "autism": "A developmental disorder of variable severity that is characterized by difficulty in social interaction and communication",
    "autumn": "The season after summer and before winter",
    "avails": "Use or take advantage of an opportunity or available resource",
    "averse": "Having a strong dislike of or opposition to something",
    "avoids": "To keep away from or stop oneself from doing something",
    "awaits": "To wait for an event or action",
    "awaked": "To stop sleeping; wake from sleep",
    "awards": "A prize or other mark of recognition given in honor of an achievement",
    "aware": "Having knowledge or perception of a situation or fact",
    "awhile": "For a short time",
    "babble": "To talk rapidly and continuously in a foolish, excited, or incomprehensible way",
    "babies": "A very young child",
    "backed": "To give financial, material, or moral support to",
    "backup": "Help or support",
    "badges": "A distinctive emblem worn as a mark of office, membership, achievement, or licensed employment",
    "badly": "In an unsatisfactory, inadequate, or unsuccessful way",
    "bagels": "A dense bread roll in the shape of a ring",
    "bakers": "A person whose trade is making and selling bread and pastries",
    "ballet": "An artistic dance form performed to music, using precise and highly formalized set steps and gestures",
    "ballot": "A process of voting, typically in secret",
    "bamboo": "A giant woody grass with hollow stems, grown widely in the tropics",
    "banana": "A long curved fruit with a yellow skin and soft, sweet, white flesh inside",
    "bandit": "A robber or outlaw belonging to a gang and typically operating in an isolated or lawless area",
    "banged": "To strike or put down something forcefully and noisily",
    "banner": "A long strip of cloth bearing a slogan or design, carried in a demonstration or procession or hung in a public place",
    "banter": "The playful and friendly exchange of teasing remarks",
    "barbed": "Having a barb or barbs",
    "barely": "Only just; almost not",
    "barges": "A long flat-bottomed boat for carrying freight on canals and rivers",
    "barley": "A hardy cereal with coarse bristles extending from the ears, used in brewing and stockfeed",
    "barrel": "A cylindrical container bulging out in the middle, traditionally made of wooden staves with metal hoops",
    "barren": "Too poor to produce much or any vegetation",
    "barter": "To exchange goods or services for other goods or services without using money",
    "basalt": "A dark, fine-grained volcanic rock",
    "basics": "The essential facts or principles of a subject or skill",
    "basket": "A container used to hold or carry things, typically made from interwoven strips of cane or wire",
    "basses": "The lowest adult male singing voice",
    "bathed": "To wash by immersing oneself in water",
    "baton": "A thin stick used by a conductor to direct an orchestra or choir",
    "batted": "To hit with a bat or similar object",
    "batter": "A mixture of flour, egg, and liquid used for baking",
    "battle": "A sustained fight between large organized armed forces",
    "bazaar": "A market in a Middle Eastern country",
    "beacon": "A fire or light set up in a high or prominent position as a warning, signal, or celebration",
    "beaded": "Decorated with or as if with beads",
    "beagle": "A small, short-legged hound with a smooth coat and long ears",
    "beamed": "To transmit a radio or television signal",
    "beanie": "A small, close-fitting hat",
    "beards": "A growth of hair on the chin and lower cheeks of a man's face",
    "bearer": "A person or thing that carries or holds something",
    "beasts": "An animal, especially a large or dangerous four-footed one",
    "beaten": "Having been defeated",
    "beauty": "A combination of qualities that pleases the aesthetic senses",
    "beaver": "A large semiaquatic rodent with a broad flat tail, noted for its habit of gnawing through trees to build dams",
    "became": "Past tense of become",
    "become": "To begin to be",
    "bedlam": "A scene of uproar and confusion",
    "beetle": "An insect with a hard, protective shell-like wing case",
    "before": "During the period of time preceding a particular event or time",
    "beggar": "A person who lives by asking for money or food",
    "begged": "To ask someone earnestly or humbly for something",
    "behalf": "In the interests of a person, group, or principle",
    "behave": "To act or conduct oneself in a specified way",
    "behind": "At or to the far side of something",
    "behold": "To see or observe a thing or person",
    "beings": "A living creature",
    "belief": "Trust, faith, or confidence in someone or something",
    "bellow": "To emit a deep loud roar, typically in pain or anger",
    "belong": "To be the property of",
    "belted": "To fasten or secure with a belt",
    "benign": "Gentle and kindly",
    "berets": "A flat, round cap of felt or cloth",
    "berths": "A ship's place at a wharf or dock",
    "beside": "At the side of; next to",
    "betray": "To expose one's country, a group, or a person to danger by treacherously giving information to an enemy",
    "better": "Of a more excellent or effective type or quality",
    "beware": "To be cautious and alert to risks or dangers",
    "beyond": "At or to the further side of",
    "biases": "Inclination or prejudice for or against one person or group",
    "bibles": "The Christian scriptures, consisting of the Old and New Testaments",
    "biceps": "A large muscle in the upper arm which turns the hand to face palm uppermost and flexes the arm and forearm",
    "bicker": "To argue about petty and trivial matters",
    "biding": "To remain in a condition or state",
    "bikers": "A person who rides a bicycle or motorcycle",
    "biking": "The activity of riding a bicycle",
    "bikini": "A two-piece swimsuit for women",
    "billet": "A place, especially a civilian's house, where soldiers are lodged temporarily",
    "binary": "Relating to, composed of, or involving two things",
    "binder": "A cover for holding loose sheets of paper together",
    "biomes": "A large, naturally occurring community of flora and fauna occupying a major habitat",
    "birchs": "A slender, fast-growing tree with thin, peeling bark",
    "birds": "A warm-blooded egg-laying vertebrate animal with feathers, wings, and a beak",
    "births": "The emergence of a baby or other young from the body of its mother; the start of life as a physically separate being",
    "bisons": "A humpbacked shaggy-haired wild ox native to North America and Europe",
    "biting": "Using the teeth to cut into something",
    "bitter": "Having a sharp, pungent taste or smell; not sweet",
    "blacks": "Of the very darkest color owing to the absence of or complete absorption of light",
    "blades": "The flat, wide section of an oar, leaf, or other object",
    "blamed": "To assign responsibility for a fault or wrong",
    "blanch": "To make white or pale by extracting color",
    "blanks": "A space left to be filled in a document",
    "blared": "To make a loud, harsh sound",
    "blasts": "A destructive wave of highly compressed air spreading outward from an explosion",
    "blazed": "To burn fiercely or brightly",
    "bleach": "To whiten by a chemical process or by exposure to sunlight",
    "bleaks": "Lacking vegetation and exposed to the elements",
    "bleeds": "To lose blood from the body as a result of injury or illness",
    "blends": "To mix a substance with another substance so that they combine together",
    "blight": "A plant disease, especially one caused by fungi",
    "blinds": "Unable to see; sightless",
    "blinks": "To shut and open the eyes quickly",
    "blithe": "Showing a casual and cheerful indifference considered to be callous or improper",
    "blocks": "A large solid piece of hard material, especially rock, stone, or wood, typically with flat surfaces on each side",
    "blonds": "A person with fair or pale yellow hair",
    "bloods": "The red liquid that circulates in the arteries and veins of humans and other vertebrate animals",
    "blooms": "A flower, especially one cultivated for its beauty",
    "blotch": "A large irregular patch or unsightly mark on the skin or another surface",
    "blouse": "A woman's upper garment resembling a shirt",
    "blower": "A device that creates a current of air",
    "blues": "Melancholic music of black American folk origin",
    "bluffs": "To try to deceive someone as to one's abilities or intentions",
    "bluish": "Having a blue tinge; slightly blue",
    "blunts": "Having a worn-down edge or point; not sharp",
    "blurbs": "A short description of a book, movie, or other product written for promotional purposes",
    "boards": "A long, thin, flat piece of wood or other hard material",
    "boasts": "To talk with excessive pride and self-satisfaction about one's achievements, possessions, or abilities",
    "boater": "A flat-topped straw hat with a brim",
    "bobbed": "To move or cause to move up and down in a quick, short movement",
    "bodies": "The physical structure of a person or an animal",
    "bogged": "To be prevented from making progress",
    "boiled": "To heat a liquid until it begins to turn into a gas",
    "boldly": "In a confident and courageous way",
    "bolted": "To run away suddenly out of control",
    "bombed": "To attack with a bomb or bombs",
    "bonbon": "A chocolate or fondant candy with a creamy filling",
    "bonded": "Joined securely to another substance",
    "bonnet": "A woman's or child's hat tied under the chin and with a brim framing the face",
    "bonnie": "Attractive or beautiful",
    "bonus": "A sum of money added to a person's wages for good performance",
    "booked": "To reserve a place, ticket, etc., for a particular time",
    "boomed": "To make a loud, deep, resonant sound",
    "boosts": "To help or encourage to increase or improve",
    "booths": "A small, temporary, tentlike structure",
    "booted": "To kick something hard",
    "border": "A line separating two countries, administrative divisions, or other areas",
    "boring": "Not interesting; tedious",
    "borrow": "To take and use something that belongs to someone else with the intention of returning it",
    "bosoms": "A woman's chest or breasts",
    "bossed": "To give orders in a domineering manner",
    "botany": "The scientific study of plants",
    "bother": "To take the trouble to do something",
    "bottle": "A container with a narrow neck, used for storing liquids",
    "bottom": "The lowest point or part of something",
    "boughs": "A main branch of a tree",
    "bought": "Past tense of buy",
    "bounce": "To spring back after hitting a surface",
    "bounds": "To walk or run with leaping strides",
    "bounty": "A sum paid for killing or capturing a person or animal",
    "bouquet": "A bunch of flowers",
    "bovine": "Relating to or affecting cattle",
    "bowels": "The part of the alimentary canal below the stomach; the intestine",
    "bowing": "To bend the head or upper body as a sign of respect, greeting, or shame",
    "bowled": "To roll a ball along the ground",
    "boxers": "A person who participates in the sport of boxing",
    "boyish": "Of or like a boy in appearance or manner",
    "braced": "To prepare for something difficult or unpleasant",
    "braids": "A length of hair made up of three or more interlaced strands",
    "brains": "An organ of soft nervous tissue contained in the skull of vertebrates",
    "braked": "To make a moving vehicle slow down or stop by using a brake",
    "branch": "A part of a tree which grows out from the trunk or a bough",
    "brands": "A type of product manufactured by a particular company under a particular name",
    "brassy": "Resembling brass in color",
    "braved": "To endure or face unpleasant conditions or behavior without showing fear",
    "bravos": "A cry of approval or encouragement",
    "brawls": "A rough or noisy fight or quarrel",
    "brawns": "Physical strength in contrast to intelligence",
    "brazen": "Bold and without shame",
    "breach": "An act of breaking or failing to observe a law or agreement",
    "breads": "A food made of flour, water, and yeast mixed together and baked",
    "breaks": "To separate into pieces as a result of a blow, shock, or strain",
    "breast": "Either of the two soft, protruding organs on the upper front of a woman's body which secrete milk after childbirth",
    "breath": "The air taken into or expelled from the lungs",
    "breeds": "A stock of animals or plants within a species having a distinctive appearance",
    "breeze": "A gentle wind",
    "brewed": "To make beer by soaking, boiling, and fermentation",
    "bribed": "To persuade someone to act in one's favor by a gift of money or other inducement",
    "bricks": "A small rectangular block typically made of fired or sun-dried clay, used in building",
    "bridal": "Of or concerning a bride or a wedding",
    "brides": "A woman on her wedding day or just before and after the event",
    "bridge": "A structure carrying a road, path, railroad, or canal across a river, ravine, road, railroad, or other obstacle",
    "briefs": "Short, close-fitting underpants",
    "bright": "Giving out or reflecting much light; shining",
    "brined": "To soak in or saturate with salty water",
    "brings": "To take or go with someone or something to a place",
    "brinks": "The extreme edge of land before a steep slope or a body of water",
    "brisks": "Active and energetic",
    "broad": "Having a distance larger than usual from side to side; wide",
    "broils": "To cook meat or fish by exposure to direct heat",
    "broke": "Past tense of break",
    "broker": "A person who buys and sells goods or assets for others",
    "bronco": "A wild or half-tamed horse of the western US",
    "bronze": "A yellowish-brown alloy of copper with up to one-third tin",
    "brooch": "An ornament fastened to clothing with a hinged pin and catch",
    "broods": "A family of young animals, especially birds, produced at one hatching or birth",
    "brook": "A small stream",
    "brooms": "A long-handled brush of bristles or twigs used for sweeping",
    "broths": "A thin soup of meat or fish stock",
    "browns": "Of a color produced by mixing red, yellow, and blue, as of dark wood or rich soil",
    "browse": "To survey goods for sale in a leisurely and casual way",
    "bruise": "An injury appearing as an area of discolored skin on the body",
    "brunch": "A late morning meal eaten instead of breakfast and lunch",
    "brunts": "The worst part or chief impact of a specified action",
    "brutal": "Savagely violent",
    "bubble": "A thin sphere of liquid enclosing air or another gas",
    "bucked": "To oppose or resist something stubbornly",
    "buckle": "A flat, typically rectangular frame with a hinged pin, used for joining the ends of a belt or strap",
    "budded": "To form a bud",
    "budget": "An estimate of income and expenditure for a set period of time",
    "buffal": "A heavily built wild ox with backswept horns",
    "buffet": "A meal consisting of several dishes from which guests serve themselves",
    "bugged": "To conceal a miniature microphone in a room or telephone",
    "builds": "To construct something by putting parts or material together",
    "bulged": "To swell or protrude to an unnatural extent",
    "bullet": "A metal projectile for firing from a rifle, revolver, or other small firearm",
    "bumble": "To act or speak in a clumsy or faltering manner",
    "bumped": "To knock or run into someone or something with a jolt",
    "bunch": "A number of things, typically of the same kind, growing or fastened together",
    "bundle": "A collection of things or quantity of material tied or wrapped up together",
    "bunked": "To sleep in a bunk or improvised bed",
    "burden": "A load, typically a heavy one",
    "bureau": "A chest of drawers",
    "burial": "The action or practice of interring a dead body",
    "burlap": "A coarse canvas woven from jute, hemp, or a similar fiber",
    "burned": "To be consumed by fire",
    "burped": "To make a noise when air from the stomach is released through the mouth",
    "burrow": "A hole or tunnel dug by a small animal, especially a rabbit, as a dwelling",
    "bursts": "To break open or apart suddenly and violently",
    "buses": "A large motor vehicle carrying passengers by road",
    "bushy": "Growing thickly",
    "busted": "To break, split, or burst something",
    "butler": "The chief male servant of a household",
    "butter": "A pale yellow edible fatty substance made by churning cream",
    "button": "A small disk or knob sewn onto a garment to fasten it by being pushed through a buttonhole",
    "buyers": "A person who makes a purchase",
    "buzzed": "To make a low, continuous humming sound",
    "bygone": "Belonging to an earlier time",
    "byline": "A line in a newspaper naming the writer of an article",
    "bypass": "A road passing around a town or its center to provide an alternative route for through traffic",
    "byways": "A road or path not in general use",
    "byword": "A person or thing cited as a notable example of a particular quality",
    "cabals": "A secret political clique or faction",
    "cabins": "A private room or compartment on a ship",
    "cabled": "To send a message by telegraph cable",
    "caches": "A collection of items of the same type stored in a hidden or inaccessible place",
    "cackle": "To laugh in a loud, harsh way",
    "cactus": "A succulent plant with a thick, fleshy stem that typically bears spines, lacks leaves, and has brilliantly colored flowers",
    "caddie": "A person who carries a golfer's clubs and provides assistance",
    "cadets": "A young trainee in the armed services or police",
    "cafes": "A small restaurant selling light meals and drinks",
    "cairns": "A mound of rough stones built as a memorial or landmark",
    "cajole": "To persuade someone to do something by sustained coaxing or flattery",
    "calico": "A plain-woven textile made from unbleached, and often not fully processed, cotton",
    "caller": "A person who pays a brief visit or makes a telephone call",
    "callow": "Inexperienced and immature",
    "calmed": "To make someone or something quiet and peaceful",
    "calves": "A young bovine animal, or the young of some other large mammals",
    "camels": "A large, long-necked ungulate mammal of arid country, with long slender legs, broad cushioned feet, and either one or two humps on the back",
    "cameos": "A piece of jewelry, typically oval in shape, consisting of a portrait in profile carved in relief on a background of a different color",
    "camera": "A device for recording visual images in the form of photographs, film, or video signals",
    "camped": "To live for a time in a tent, especially while on vacation",
    "camper": "A person who spends a vacation in a tent",
    "canals": "An artificial waterway constructed to allow the passage of boats or ships inland or to convey water for irrigation",
    "canary": "A small, brightly colored finch with a melodious song, native to the Canary Islands",
    "cancel": "To decide or announce that an arranged event will not take place",
    "cancer": "A disease caused by an uncontrolled division of abnormal cells in a part of the body",
    "candid": "Truthful and straightforward; frank",
    "candle": "A cylinder or block of wax or tallow with a central wick that is lit to produce light as it burns",
    "canine": "Relating to or resembling a dog or dogs",
    "canopy": "An ornamental cloth covering hung or held up over something, especially a throne or bed",
    "canyon": "A deep gorge, typically one with a river flowing through it",
    "capers": "A playful skipping movement",
    "capita": "A head or a person, used in statistics per capita",
    "capsid": "The protein shell of a virus",
    "captor": "A person who captures someone or something",
    "carafe": "An open-topped glass flask used for serving wine or water in a restaurant",
    "carats": "A unit of weight for precious stones and pearls, equivalent to 200 milligrams",
    "carbon": "A nonmetallic chemical element with atomic number 6 that occurs as diamond and graphite",
    "carded": "To comb and clean raw wool or cotton before spinning",
    "careen": "To turn a ship on its side for cleaning, caulking, or repair",
    "career": "An occupation undertaken for a significant period of a person's life and with opportunities for progress",
    "caress": "To touch or stroke gently or lovingly",
    "cargo": "Goods carried on a ship, aircraft, or motor vehicle",
    "carols": "A religious folk song or popular hymn, particularly one associated with Christmas",
    "carpal": "Relating to the bones in the wrist",
    "carpet": "A floor covering made from thick woven fabric",
    "carrot": "A tapering orange-colored root eaten as a vegetable",
    "cartel": "An association of manufacturers or suppliers with the purpose of maintaining prices at a high level and restricting competition",
    "carton": "A light box or container, typically one made of cardboard",
    "carved": "To cut into a hard material to produce an object or design",
    "casein": "The main protein present in milk and in cheese",
    "casino": "A building used for gambling",
    "casket": "A small ornamental box or chest for holding jewels, letters, or other valued objects",
    "caster": "A person or machine that casts something",
    "castle": "A large building, typically of the medieval period, fortified against attack with thick walls, battlements, towers, and often a moat",
    "casual": "Relaxed and unconcerned",
    "catchy": "Instantly appealing and memorable",
    "caters": "To provide food and drink, typically at social events and in a professional capacity",
    "cation": "A positively charged ion",
    "catnap": "A short sleep during the day",
    "catnip": "A plant of the mint family that is attractive to cats",
    "cattle": "Large ruminant animals with horns and cloven hoofs, domesticated for meat or milk",
    "caucus": "A meeting of the members of a legislative body who are members of a particular political party",
    "caught": "Past tense of catch",
    "causal": "Relating to or acting as a cause",
    "caused": "To make something happen",
    "caveat": "A warning or proviso of specific stipulations, conditions, or limitations",
    "cavern": "A large cave or chamber in a cave",
    "caviar": "The pickled roe of sturgeon or other large fish, eaten as a delicacy",
    "cavity": "An empty space within a solid object",
    "ceased": "To come or bring to an end",
    "cedars": "A tall, wide-spreading coniferous tree with needle-like leaves",
    "celebs": "Short for celebrities",
    "celery": "A cultivated plant of the parsley family, with closely packed succulent leafstalks that are eaten raw or cooked",
    "cellar": "A room below ground level in a house, often used for storing wine or coal",
    "cement": "A powdery substance made with calcined lime and clay, mixed with water to form mortar or concrete",
    "dagger": "A short, pointed knife used as a weapon",
    "damage": "Physical harm that impairs the value, usefulness, or normal function of something",
    "dancer": "A person who dances",
    "danger": "The possibility of suffering harm or injury",
    "darken": "To make or become dark or darker",
    "darling": "A beloved or endearing person",
    "dazzle": "To blind temporarily with a bright light",
    "dealer": "A person who buys and sells goods",
    "debate": "A formal discussion on a particular topic",
    "decade": "A period of ten years",
    "decide": "To make a choice from a number of alternatives",
    "defeat": "To win a victory over someone in a battle or contest",
    "defect": "A shortcoming, imperfection, or lack",
    "defend": "To resist an attack made on someone or something",
    "define": "To state or describe the exact nature or scope of",
    "degree": "A unit of measurement of angles or temperature",
    "delete": "To remove or erase something",
    "delight": "Great pleasure",
    "demand": "An insistent and peremptory request",
    "denial": "The action of declaring something to be untrue",
    "dental": "Relating to the teeth or dentistry",
    "depart": "To leave, especially to start a journey",
    "depend": "To rely on someone or something",
    "deputy": "A person appointed to act for another",
    "desert": "A dry, barren area of land",
    "design": "A plan or drawing produced to show the look and function of something",
    "desire": "A strong feeling of wanting to have something",
    "detail": "An individual feature, fact, or item",
    "detect": "To discover or identify the presence of something",
    "device": "A thing made or adapted for a particular purpose",
    "devote": "To give all or most of one's time or resources to a person or activity",
    "diary": "A book in which one keeps a daily record of events and experiences",
    "differ": "To be unlike or dissimilar",
    "digital": "Relating to or using signals or information represented by discrete values",
    "dinner": "The main meal of the day, taken either around midday or in the evening",
    "direct": "Extending or moving from one place to another without changing direction or stopping",
    "dismay": "Consternation and distress, typically that caused by something unexpected",
    "dispute": "A disagreement, argument, or debate",
    "distant": "Far away in space or time",
    "divide": "To separate or be separated into parts",
    "doctor": "A person who is qualified to treat people who are ill",
    "dollar": "The basic monetary unit of the US, Canada, Australia, and certain countries in the Pacific",
    "domain": "An area of territory owned or controlled by a ruler or government",
    "donate": "To give money or goods to a charity or good cause",
    "double": "Consisting of two equal, identical, or similar parts or things",
    "dragon": "A mythical monster like a giant reptile, often shown breathing fire",
    "drawer": "A box-shaped storage compartment without a lid that slides horizontally",
    "dreamy": "Having a magical or pleasantly unreal quality; dreamlike",
    "dressy": "Smart and fashionable in dress",
    "drink": "To take a liquid into the mouth and swallow",
    "driver": "A person who drives a vehicle",
    "drowsy": "Sleepy and lethargic; half asleep",
    "drummer": "A person who plays a drum or drums",
    "drying": "Becoming dry",
    "dynamo": "A machine for converting mechanical energy into electrical energy; a generator",
    "eager": "Strongly wanting to do or have something",
    "eagle": "A large bird of prey with a massive hooked bill and long broad wings",
    "earthy": "Resembling or suggestive of earth or soil",
    "easily": "Without difficulty or effort",
    "easter": "The most important and oldest festival of the Christian Church, celebrating the resurrection of Jesus",
    "eating": "Putting food into the mouth and chewing and swallowing it",
    "echoed": "Repeated or reverberated a sound",
    "ecology": "The branch of biology that deals with the relations of organisms to one another and to their physical surroundings",
    "editor": "A person who is in charge of and determines the final content of a publication",
    "effect": "A change which is a result or consequence of an action or other cause",
    "effort": "A vigorous or determined attempt",
    "either": "Used before the first of two alternatives specified",
    "elbow": "The joint between the forearm and the upper arm",
    "elder": "A person of greater age than someone specified",
    "elegant": "Graceful and stylish in appearance or manner",
    "element": "A fundamental, essential, or irreducible part of a composite entity",
    "eleven": "Equivalent to the sum of six and five; one more than ten; 11",
    "emerge": "To move out of or away from something and become visible",
    "empire": "An extensive group of states or countries under a single supreme authority",
    "employ": "To give work to someone and pay them for it",
    "enable": "To give someone the authority or means to do something",
    "ending": "An end or final part of something",
    "endure": "To suffer something painful or difficult patiently",
    "energy": "The strength and vitality required for sustained physical or mental activity",
    "engage": "To occupy, attract, or involve someone's interest or attention",
    "engine": "A machine with moving parts that converts power into motion",
    "enigma": "A person or thing that is mysterious, puzzling, or difficult to understand",
    "enjoy": "To take delight or pleasure in an activity or occasion",
    "enlist": "To enroll or be enrolled in the armed services",
    "enough": "As much or as many as required",
    "ensure": "To make certain that something will occur or be the case",
    "entire": "With no part left out; whole",
    "entry": "An act of going or coming in",
    "envy": "A feeling of discontented or resentful longing aroused by someone else's possessions, qualities, or luck",
    "episode": "An event or a group of events occurring as part of a larger sequence",
    "equally": "In the same manner or to the same extent",
    "equity": "The quality of being fair and impartial",
    "eraser": "A piece of rubber or plastic used to rub out something written",
    "errand": "A short journey undertaken in order to deliver or collect something",
    "escape": "To break free from confinement or control",
    "estate": "An area or amount of land or property",
    "ethics": "Moral principles that govern a person's behavior",
    "evenly": "In a level and regular manner",
    "event": "A thing that happens, especially one of importance",
    "every": "Used to refer to all the individual members of a set without exception",
    "exact": "Not approximated in any way; precise",
    "exam": "A medical test of a specified kind",
    "exceed": "To be greater in number or size than a quantity, level, or limit",
    "except": "Not including; other than",
    "excess": "An amount of something that is more than necessary, permitted, or desirable",
    "excuse": "To attempt to lessen the blame attaching to a fault or offense",
    "exempt": "Free from an obligation or liability imposed on others",
    "exotic": "Originating in or characteristic of a distant foreign country",
    "expand": "To become or make larger or more extensive",
    "expect": "To regard something as likely to happen",
    "expert": "A person who has a comprehensive and authoritative knowledge of or skill in a particular area",
    "export": "To send goods or services to another country for sale",
    "expose": "To make something visible by uncovering it",
    "extend": "To cause to cover a wider area; make larger",
    "extent": "The area covered by something",
    "extra": "Added to an existing or usual amount or number",
    "fabric": "Cloth produced by weaving or knitting textile fibers",
    "facial": "Of or affecting the face",
    "factor": "A circumstance, fact, or influence that contributes to a result",
    "fading": "Gradually growing faint and disappearing",
    "failing": "A weakness, especially in character; a shortcoming",
    "fairly": "With justice",
    "falcon": "A bird of prey with long pointed wings and a notched beak",
    "fallen": "Having dropped or come down from a higher place",
    "family": "A group consisting of parents and children living together in a household",
    "famous": "Known about by many people",
    "farmer": "A person who owns or manages a farm",
    "faster": "More quick",
    "father": "A man in relation to his child or children",
    "fault": "An unattractive or unsatisfactory feature, especially in a piece of work or in a person's character",
    "favour": "Approval, support, or liking for someone or something",
    "feared": "Was afraid of someone or something as likely to be dangerous, painful, or threatening",
    "feather": "Any of the flat appendages growing from a bird's skin and forming its plumage",
    "fellow": "A man or boy",
    "female": "Of or denoting the sex that can bear offspring or produce eggs",
    "fender": "A low frame bordering a fireplace to keep in falling logs or coal",
    "ferry": "A boat or ship for conveying passengers and goods, especially across a river or short sea journey",
    "fever": "An abnormally high body temperature, usually accompanied by shivering, headache, and in severe instances, delirium",
    "fiber": "A thread or filament from which a vegetable tissue, mineral substance, or textile is formed",
    "fiction": "Literature in the form of prose that describes imaginary events and people",
    "field": "An area of open land, especially one planted with crops or pasture",
    "fierce": "Having or displaying an intense or ferocious aggressiveness",
    "figure": "A number, especially one which forms part of official statistics or relates to the financial performance of a company",
    "filing": "The action of placing documents in a file",
    "filter": "A porous device for removing impurities or solid particles from a liquid or gas passed through it",
    "finger": "Each of the four slender jointed parts attached to either hand",
    "finish": "To bring a task or activity to an end; complete",
    "fiscal": "Relating to government revenue, especially taxes",
    "fishing": "The activity of catching fish, either for food or as a sport",
    "fitted": "Made, done, or changed to suit a particular purpose or situation",
    "fixing": "The action of fastening something in place",
    "flavor": "The distinctive taste of a food or drink",
    "flight": "The action or process of flying through the air",
    "floating": "Resting on the surface of a liquid without sinking",
    "floral": "Decorated with or depicting flowers",
    "flower": "The seed-bearing part of a plant, consisting of reproductive organs that are typically surrounded by a brightly colored corolla and a green calyx",
    "flying": "Moving or able to move through the air with wings",
    "follow": "To go or come after a person or thing proceeding ahead",
    "forbid": "To refuse to allow something",
    "forest": "A large area covered chiefly with trees and undergrowth",
    "forget": "To fail to remember",
    "formal": "Done in accordance with rules of convention or etiquette",
    "format": "The way in which something is arranged or set out",
    "former": "Having previously been a particular thing",
    "fortune": "A large amount of money or assets",
    "fossil": "The remains or impression of a prehistoric plant or animal embedded in rock and preserved in petrified form",
    "foster": "To encourage or promote the development of something",
    "freeze": "To be turned into ice or another solid as a result of extreme cold",
    "french": "Relating to France or its people or language",
    "frequent": "Occurring or done on many occasions, in many cases, or in quick succession",
    "friend": "A person whom one knows and with whom one has a bond of mutual affection",
    "fright": "A sudden intense feeling of fear",
    "frozen": "Having turned into ice as a result of extreme cold",
    "frugal": "Sparing or economical with regard to money or food",
    "frying": "The process of cooking food in hot fat or oil",
    "future": "The time or a period of time following the moment of speaking or writing; time regarded as still to come",
    "galaxy": "A system of millions or billions of stars, together with gas and dust, held together by gravitational attraction",
    "gallon": "A unit of volume for liquid measure equal to four quarts",
    "gamble": "Play games of chance for money; bet",
    "garage": "A building for housing a motor vehicle or vehicles",
    "garden": "A piece of ground adjoining a house, used for growing flowers, fruit, or vegetables",
    "garlic": "A strong-smelling pungent-tasting bulb, used as a flavoring in cooking",
    "gather": "Come together; assemble or accumulate",
    "gazebo": "A freestanding open-sided structure for enjoying the view",
    "gender": "The state of being male or female",
    "genius": "Exceptional intellectual or creative power or other natural ability",
    "gentle": "Having or showing a mild, kind, or tender temperament",
    "genuine": "Truly what something is said to be; authentic",
    "german": "Relating to Germany, its people, or their language",
    "gifted": "Having exceptional talent or natural ability",
    "ginger": "A hot, fragrant spice made from the rhizome of a plant",
    "glacier": "A slowly moving mass or river of ice formed by the accumulation and compaction of snow on mountains",
    "glance": "Take a brief or hurried look",
    "glassy": "Having the physical characteristics of glass, especially in being smooth and somewhat reflective",
    "global": "Relating to the whole world; worldwide",
    "glory": "High renown or honor won by notable achievements",
    "glossy": "Shiny and smooth",
    "glove": "A covering for the hand worn for protection against cold or dirt",
    "golden": "Made of or colored like gold",
    "google": "To use the Google search engine to find information on the internet",
    "gospel": "The teaching or revelation of Christ",
    "gossip": "Casual or unconstrained conversation or reports about other people",
    "govern": "Conduct the policy, actions, and affairs of a state, organization, or people",
    "guilty": "Responsible for a specified wrongdoing",
    "guitar": "A stringed musical instrument with a fretted fingerboard",
    "hammer": "A tool with a heavy metal head mounted at right angles at the end of a handle",
    "handle": "The part by which a thing is held, carried, or controlled",
    "harvest": "The process or period of gathering in crops",
    "hazard": "A danger or risk",
    "health": "The state of being free from illness or injury",
    "heaven": "A place regarded in various religions as the abode of God and the angels",
    "height": "The measurement from base to top or head to foot",
    "hidden": "Kept out of sight; concealed",
    "hiking": "The activity of going for long walks, especially in the country or woods",
    "history": "The study of past events, particularly in human affairs",
    "home": "The place where one lives permanently",
    "honest": "Free of deceit and untruthfulness; sincere",
    "horror": "An intense feeling of fear, shock, or disgust",
    "humble": "Having or showing a modest or low estimate of one's own importance",
    "husband": "A married man considered in relation to his spouse",
    "hybrid": "A thing made by combining two different elements",
    "iconic": "Widely recognized and well-established",
    "ignore": "Refuse to take notice of or acknowledge",
    "igloo": "A dome-shaped Eskimo house, typically built from blocks of solid snow",
    "illegal": "Contrary to or forbidden by law",
    "impact": "The action of one object coming forcibly into contact with another",
    "import": "Bring (goods or services) into a country from abroad for sale",
    "impose": "Force (something unwelcome or unfamiliar) to be accepted or put in place",
    "impress": "Make (someone) feel admiration and respect",
    "income": "Money received, especially on a regular basis, for work or through investments",
    "index": "An alphabetical list of names, subjects, etc., with references to the places where they occur",
    "indoor": "Situated, conducted, or used within a building or under cover",
    "infant": "A very young child or baby",
    "inform": "Give (someone) facts or information; tell",
    "inject": "Introduce (a drug or other substance) into the body with a syringe",
    "injury": "An instance of being injured",
    "inmate": "A person confined to an institution such as a prison or hospital",
    "inning": "A division of a game during which both sides have a turn at batting",
    "input": "What is put in, taken in, or operated on by any process or system",
    "insect": "A small arthropod animal that has six legs and generally one or two pairs of wings",
    "insert": "Place, fit, or thrust (something) into another thing",
    "inside": "The inner side or surface of something",
    "insist": "Demand something forcefully, not accepting refusal",
    "insure": "Arrange for compensation in the event of damage to or loss of (property), or injury to or the death of (someone)",
    "intact": "Not damaged or impaired in any way; complete",
    "intake": "An amount of food, air, or another substance taken into the body",
    "intend": "Have (a course of action) as one's purpose or objective; plan",
    "intern": "A student or trainee who works, sometimes without pay, in order to gain work experience",
    "into": "Expressing movement or action with the result that someone or something becomes enclosed or surrounded by something else",
    "intron": "A segment of a DNA or RNA molecule which does not code for proteins",
    "invade": "Enter (a country or region) so as to subjugate or occupy it",
    "invent": "Create or design (something that has not existed before); be the originator of",
    "invest": "Expend money with the expectation of achieving a profit or material result",
    "invite": "Make a polite, formal, or friendly request to (someone) to go somewhere or to do something",
    "ironic": "Using or characterized by irony",
    "island": "A piece of land surrounded by water",
    "itself": "Used as the object of a verb or preposition to refer to a thing or animal previously mentioned as the subject of the clause",
    "jacket": "An outer garment extending either to the waist or the hips, typically having sleeves and a fastening down the front",
    "jaguar": "A large, heavily built cat that has a yellowish-brown coat with black spots, found mainly in the dense forests of Central and South America",
    "jargon": "Special words or expressions used by a profession or group that are difficult for others to understand",
    "jaunty": "Having or expressing a lively, cheerful, and self-confident manner",
    "jealous": "Feeling or showing envy of someone or their achievements and advantages",
    "jelly": "A fruit-flavored dessert made by warming and then cooling a liquid containing gelatin or a similar setting agent",
    "jersey": "A knitted garment typically with long sleeves, worn over the upper body",
    "jester": "A professional joker or “fool” at a medieval court, typically wearing a cap with bells on it",
    "jigsaw": "A puzzle consisting of a picture printed on cardboard or wood and cut into various pieces of different shapes that have to be fitted together",
    "jingle": "A light ringing sound such as that made by metal objects being shaken together",
    "jockey": "A person who rides in horse races, especially as a profession",
    "jolly": "Happy and cheerful",
    "jotter": "A small pad or notebook used for notes or jottings",
    "joyful": "Feeling, expressing, or causing great pleasure and happiness",
    "judged": "Formed an opinion or conclusion about",
    "juicy": "Full of juice; succulent",
    "jumble": "An untidy collection or pile of things",
    "jumped": "Push oneself off a surface and into the air by using the muscles in one's legs and feet",
    "jungle": "An area of land overgrown with dense forest and tangled vegetation, typically in the tropics",
    "junior": "For or denoting young or younger people",
    "junkie": "A drug addict",
    "jurist": "An expert in or writer on law",
    "justly": "In a way that is fair and deserved",
    "karate": "A system of unarmed combat using the hands and feet to deliver and block blows, widely practiced as a sport",
    "keeper": "A person who manages or looks after something or someone",
    "kennel": "A small shelter for a dog",
    "kernel": "A softer, usually edible part of a nut, seed, or fruit stone contained within its hard shell",
    "kettle": "A container or device in which water is boiled, having a lid, spout, and handle",
    "keypad": "A small set of buttons or keys fixed in a block, used for inputting data",
    "kidnap": "Take (someone) away illegally by force, typically to obtain a ransom",
    "kidney": "Each of a pair of organs in the abdominal cavity of mammals, birds, and reptiles, that excrete urine",
    "kindle": "Light or set on fire",
    "kindly": "In a kind manner",
    "kingly": "Associated with or typical of a king; regal",
    "kiosk": "A small open-fronted hut or cubicle from which newspapers, refreshments, tickets, etc., are sold",
    "kitten": "A young cat",
    "knack": "An acquired or natural skill at performing a task",
    "kneads": "Work (moistened flour or clay) into dough or paste with the hands",
    "knee": "The joint between the thigh and the lower leg in humans",
    "knife": "An instrument composed of a blade fixed into a handle, used for cutting or as a weapon",
    "knight": "A man awarded a nonhereditary title by a sovereign in recognition of merit or service",
    "knocks": "Strike a surface noisily to attract attention",
    "knotty": "Full of knots",
    "knower": "A person who knows something",
    "kosher": "Food satisfying the requirements of Jewish law",
    "labels": "A small piece of paper, fabric, plastic, or similar material attached to an object and giving information about it",
    "labour": "Work, especially physical work",
    "ladder": "A piece of equipment consisting of a series of bars or steps between two upright lengths of wood, metal, or rope, used for climbing up or down",
    "ladies": "Polite or formal way to refer to women",
    "lagoon": "A stretch of salt water separated from the sea by a low sandbank or coral reef",
    "lament": "A passionate expression of grief or sorrow",
    "laptop": "A computer that is portable and suitable for use while traveling",
    "large": "Of considerable or relatively great size, extent, or capacity",
    "lastly": "In the last place; finally",
    "lately": "Recently; not long ago",
    "latent": "Existing but not yet developed or manifest; hidden or concealed",
    "latest": "The most recent news or fashion",
    "latter": "Occurring or situated nearer to the end of something than to the beginning",
    "laughs": "Make the spontaneous sounds and movements of the face and body that are the instinctive expressions of lively amusement",
    "launch": "Set (a boat) in motion by pushing it or allowing it to roll into the water",
    "lawful": "Conforming to, permitted by, or recognized by law or rules",
    "lawyer": "A person who practices or studies law; an attorney or a counselor",
    "layers": "A sheet, quantity, or thickness of material, typically one of several, covering a surface or body",
    "layout": "The way in which the parts of something are arranged or laid out",
    "lazily": "In a manner that shows an unwillingness to use energy",
    "leader": "The person who leads or commands a group, organization, or country",
    "league": "A collection of people, countries, or groups that combine for a particular purpose",
    "leaned": "Be in or move into a sloping position",
    "learns": "Gain or acquire knowledge of or skill in (something) by study, experience, or being taught",
    "leaves": "The main organ of photosynthesis and transpiration in higher plants",
    "legacy": "An amount of money or property left to someone in a will",
    "legend": "A traditional story sometimes popularly regarded as historical but not authenticated",
    "length": "The measurement or extent of something from end to end",
    "lessen": "Make or become less; diminish",
    "lesson": "A period of learning or teaching",
    "lethal": "Sufficient to cause death",
    "letter": "A character representing one or more of the sounds used in speech",
    "liable": "Responsible by law; legally answerable",
    "libyan": "Relating to Libya or its people",
    "lichen": "A simple slow-growing plant that typically forms a low crustlike, leaflike, or branching growth on rocks, walls, and trees",
    "licked": "Pass the tongue over (something) in order to taste, moisten, or clean it",
    "lifted": "Raise to a higher position or level",
    "light": "The natural agent that stimulates sight and makes things visible",
    "likely": "Such as well might happen or be true; probable",
    "limits": "A point or level beyond which something does not or may not extend or pass",
    "linear": "Arranged in or extending along a straight or nearly straight line",
    "linen": "Cloth woven from flax",
    "linger": "Stay in a place longer than necessary because of a reluctance to leave",
    "linked": "Connected, joined, or attached to something else",
    "liquid": "A substance that flows freely but is of constant volume, having a consistency like that of water or oil",
    "listed": "Entered on a list",
    "listen": "Give one's attention to a sound",
    "litter": "Trash, such as paper, cans, and bottles, that is left lying in an open or public place",
    "little": "Small in size, amount, or degree",
    "lively": "Full of life and energy; active and outgoing",
    "living": "The state of being alive",
    "loaded": "Carrying or bearing a load, especially a large one",
    "loaned": "Lent something to someone",
    "locals": "A person who lives in a particular area",
    "locate": "Discover the exact place or position of",
    "locked": "Fastened or secured with a lock",
    "locker": "A small, usually metal compartment that can be locked, especially one at a gym or school",
    "locust": "A large, mainly tropical grasshopper with strong powers of flight",
    "lodged": "Become stuck or fixed in a particular place",
    "logged": "Entered information about an event in a log",
    "lonely": "Sad because one has no friends or company",
    "longer": "Of a great distance or duration",
    "loomed": "Appeared as a vague form, especially one that is large or threatening",
    "loosen": "Make something less tight",
    "losing": "Being deprived of or ceasing to have or retain something",
    "loudly": "In a way that produces much noise",
    "lovely": "Exquisitely beautiful",
    "loving": "Feeling or showing love or great care",
    "lowest": "Of the least possible degree, amount, or intensity",
    "loyal": "Giving or showing firm and constant support or allegiance to a person or institution",
    "lumber": "Wood that has been processed into beams and planks",
    "lumped": "Put in an indiscriminate mass or group",
    "lunar": "Of, determined by, or resembling the moon",
    "lunch": "A meal eaten in the middle of the day",
    "luxury": "A state of great comfort or elegance, especially when involving great expense",
    "lyrics": "The words of a song",
    "pacify": "To quell the anger, agitation, or excitement of",
    "paddle": "A short pole with a broad blade at one or both ends, used for propelling a canoe or small boat",
    "parade": "A public procession, especially one celebrating a special day or event",
    "parcel": "A thing or collection of things wrapped in paper in order to be carried or sent by mail",
    "pardon": "The action of forgiving or being forgiven for an error or offense",
    "parent": "A father or mother",
    "parish": "A small administrative district typically having its own church and a priest or pastor",
    "parlor": "A sitting room in a private house",
    "parody": "An imitation of the style of a particular writer, artist, or genre with deliberate exaggeration for comic effect",
    "parrot": "A bird, often vividly colored, known for its ability to mimic human speech",
    "pastel": "A soft and delicate shade of a color",
    "pastor": "A minister in charge of a Christian church or congregation",
    "pastry": "A dough of flour, water, and shortening that may be savory or sweetened",
    "patent": "A government authority or license conferring a right or title for a set period, especially the sole right to make, use, or sell an invention",
    "patrol": "To keep watch over an area by regularly walking or traveling around it",
    "patron": "A person who gives financial or other support to a person, organization, cause, or activity",
    "payout": "A large payment of money, especially as a prize or compensation",
    "peanut": "The oval seed of a South American plant, often eaten roasted or salted",
    "peasant": "A poor farmer of low social status who owns or rents a small piece of land for cultivation",
    "pelvis": "The large bony frame at the base of the spine to which the hind limbs or legs are attached",
    "pencil": "An instrument for writing or drawing, consisting of a thin stick of graphite enclosed in a long thin piece of wood",
    "people": "Human beings in general or considered collectively",
    "pepper": "A hot-tasting pungent condiment obtained from the dried berries of a climbing vine",
    "period": "A length or portion of time",
    "permit": "To give authorization or consent to someone to do something",
    "person": "A human being regarded as an individual",
    "petrol": "A light fuel oil obtained by distilling petroleum, used in internal combustion engines",
    "pharma": "The pharmaceutical industry",
    "phased": "Carried out in gradual stages",
    "phoenix": "A mythical bird that cyclically regenerates or is reborn from its own ashes",
    "phrase": "A small group of words standing together as a conceptual unit",
    "picket": "A person or group of people standing outside a workplace trying to persuade others not to enter during a strike",
    "picnic": "An outing or occasion that involves taking a packed meal to be eaten outdoors",
    "picture": "A painting, drawing, or photograph",
    "piece": "A portion of an object or of material, produced by cutting, tearing, or breaking the whole",
    "pierce": "To make a hole in something with a sharp point",
    "pigeon": "A stout-bodied bird with a short neck, often found in cities",
    "pillar": "A tall vertical structure of stone, wood, or metal, used as a support for a building",
    "pillow": "A rectangular cloth bag stuffed with soft material, used to support the head when lying down",
    "pilot": "A person who operates the flying controls of an aircraft",
    "pinball": "A game in which players score points by manipulating a ball on a inclined board with flippers",
    "piracy": "The practice of attacking and robbing ships at sea",
    "pistol": "A small firearm designed to be held in one hand",
    "piston": "A disc or short cylinder fitting closely within a tube in which it moves up and down against a liquid or gas",
    "pixel": "A minute area of illumination on a display screen, one of many from which an image is composed",
    "pizza": "A dish of Italian origin consisting of a flat, round base of dough baked with a topping of tomatoes, cheese, and other ingredients",
    "place": "A particular position, point, or area in space; a location",
    "placid": "Not easily upset or excited",
    "plague": "A contagious bacterial disease characterized by fever and delirium",
    "planet": "A celestial body moving in an elliptical orbit around a star",
    "plasma": "The colorless fluid part of blood, lymph, or milk, in which corpuscles or fat globules are suspended",
    "plated": "Covered with a thin layer of metal, such as gold or silver",
    "player": "A person who takes part in a sport or game",
    "please": "To cause to feel happy and satisfied",
    "pledge": "A solemn promise or undertaking",
    "plenty": "A large or sufficient amount or quantity; more than enough",
    "plight": "A dangerous, difficult, or otherwise unfortunate situation",
    "plough": "A large farming implement with one or more blades fixed in a frame, used to turn over soil",
    "pocket": "A small bag sewn into or on clothing so as to form part of it, used for carrying small articles",
    "poetry": "Literary work in which special intensity is given to the expression of feelings and ideas by the use of distinctive style and rhythm",
    "point": "The tapered, sharp end of a tool, weapon, or other object",
    "poison": "A substance that is capable of causing the illness or death of a living organism when introduced or absorbed",
    "police": "The civil force of a national or local government, responsible for the prevention and detection of crime and the maintenance of public order",
    "policy": "A course or principle of action adopted or proposed by an organization or individual",
    "polish": "To make the surface of something smooth and shiny by rubbing it",
    "polite": "Having or showing behavior that is respectful and considerate of other people",
    "pollen": "A fine powdery substance, typically yellow, consisting of microscopic grains discharged from the male part of a flower",
    "portal": "A doorway, gate, or other entrance, especially a large and imposing one",
    "portfolio": "A large, thin, flat case for carrying loose sheets of paper or drawings",
    "poster": "A large printed picture used for decoration",
    "potato": "A starchy plant tuber which is one of the most important food crops, cooked and eaten as a vegetable",
    "potent": "Having great power, influence, or effect",
    "potion": "A liquid with healing, magical, or poisonous properties",
    "pounce": "To spring or swoop suddenly so as to seize or attack",
    "powder": "Fine, dry particles produced by the grinding, crushing, or disintegration of a solid substance",
    "power": "The ability to do something or act in a particular way",
    "praise": "To express warm approval or admiration of",
    "prayer": "A solemn request for help or expression of thanks addressed to God or another deity",
    "preach": "To deliver a sermon or religious address to an assembled group of people",
    "prefer": "To like one thing or person better than another or others; to tend to choose",
    "prefix": "A word, letter, or number placed before another",
    "preset": "Set or adjusted in advance of its use",
    "press": "To move or cause to move into a position of contact with something by exerting continuous physical force",
    "pretty": "Attractive in a delicate way without being truly beautiful or handsome",
    "price": "The amount of money expected, required, or given in payment for something",
    "pride": "A feeling of deep pleasure or satisfaction derived from one's own achievements",
    "priest": "An ordained minister of the Catholic, Orthodox, or Anglican Church having the authority to perform certain rites and administer certain sacraments",
    "primal": "Relating to an early stage in evolutionary development; primeval",
    "prime": "Of first importance; main",
    "prince": "The son of a monarch",
    "print": "To produce a book, newspaper, etc. by a mechanical process involving the transfer of text or designs to paper",
    "prison": "A building in which people are legally held as a punishment for a crime they have committed or while awaiting trial",
    "prize": "Something given as a reward for victory or superiority in a contest or competition",
    "probe": "To physically explore or examine something with the hands or an instrument",
    "profit": "A financial gain, especially the difference between the amount earned and the amount spent in buying, operating, or producing something",
    "prompt": "To cause someone to take a course of action",
    "proof": "Evidence or argument establishing or helping to establish a fact or the truth of a statement",
    "proper": "Truly what something is said to be; authentic",
    "proton": "A stable subatomic particle occurring in all atomic nuclei, with a positive electric charge",
    "proved": "Demonstrated the truth or existence of something by evidence or argument",
    "proven": "Demonstrated by evidence or argument to be true or to exist",
    "public": "Of or concerning the people as a whole",
    "puddle": "A small pool of liquid, especially of rainwater on the ground",
    "pulley": "A wheel with a grooved rim around which a cord passes, used to raise heavy weights",
    "punch": "To strike with the fist",
    "punish": "To inflict a penalty or sanction on someone for an offense, transgression, or fault",
    "puppet": "A movable model of a person or animal that is typically moved either by strings controlled from above or by a hand inside it",
    "purely": "In a pure manner; wholly and completely",
    "purity": "Freedom from adulteration or contamination",
    "purple": "A color intermediate between red and blue",
    "pursue": "To follow someone or something in order to catch or attack them",
    "puzzle": "A game, toy, or problem designed to test ingenuity or knowledge",
}
sixes_list = sixes_json.keys()
