CREATE DATABASE `wordle` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE `wordle`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_id` VARCHAR(255) NOT NULL UNIQUE,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `email` VARCHAR(255) DEFAULT NULL,
  `xp` INT UNSIGNED NOT NULL DEFAULT 0,
  `coins` INT UNSIGNED NOT NULL DEFAULT 500,
  `games_played` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  PRIMARY KEY `pk_id` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
